// This file is auto-generated by @flyxc/windy-types update script.
// Source package: @windycom/plugin-devtools@3.0.4
// DO NOT EDIT DIRECTLY.

import type * as WindyExports from './windy-exports';

declare const W: typeof WindyExports;

declare module '@plugins/*';
declare module '@capacitor/*';
declare module '@windy-types/*';

declare module '@windy/envVariables' {
  export * from './types/envVariables';
}

declare module '@windy/envVariables.d' {
  export * from './types/envVariables';
}

declare module '@windy/iconfont' {
  export * from './types/iconfont';
}

declare module '@windy/iconfont.d' {
  export * from './types/iconfont';
}

declare module '@windy/interfaces' {
  export * from './types/interfaces';
}

declare module '@windy/interfaces.d' {
  export * from './types/interfaces';
}

declare module '@windy/lang-files' {
  export * from './types/lang-files';
}

declare module '@windy/lang-files.d' {
  export * from './types/lang-files';
}

declare module '@windy/leaflet-gl' {
  export * from './types/leaflet-gl';
}

declare module '@windy/leaflet-gl.d' {
  export * from './types/leaflet-gl';
}

declare module '@leafletGl' {
  export * from './types/leaflet-gl';
}

declare module '@windy/leaflet' {
  export * from './types/leaflet';
}

declare module '@windy/leaflet.d' {
  export * from './types/leaflet';
}

declare module '@windy/node-forecast-v3' {
  export * from './types/node-forecast-v3';
}

declare module '@windy/node-forecast-v3.d' {
  export * from './types/node-forecast-v3';
}

declare module '@windy/types' {
  export * from './types/types';
}

declare module '@windy/types.d' {
  export * from './types/types';
}

declare module '@windy/AccessProducts' {
  export * from './types/client/AccessProducts';
}

declare module '@windy/AccessProducts.d' {
  export * from './types/client/AccessProducts';
}

declare module '@windy/client/AccessProducts' {
  export * from './types/client/AccessProducts';
}

declare module '@windy/client/AccessProducts.d' {
  export * from './types/client/AccessProducts';
}

declare module '@windy/AromeProduct' {
  export * from './types/client/AromeProduct';
}

declare module '@windy/AromeProduct.d' {
  export * from './types/client/AromeProduct';
}

declare module '@windy/client/AromeProduct' {
  export * from './types/client/AromeProduct';
}

declare module '@windy/client/AromeProduct.d' {
  export * from './types/client/AromeProduct';
}

declare module '@windy/BottomSlide' {
  export * from './types/client/BottomSlide';
}

declare module '@windy/BottomSlide.d' {
  export * from './types/client/BottomSlide';
}

declare module '@windy/client/BottomSlide' {
  export * from './types/client/BottomSlide';
}

declare module '@windy/client/BottomSlide.d' {
  export * from './types/client/BottomSlide';
}

declare module '@windy/BottomSveltePlugins' {
  export * from './types/client/BottomSveltePlugins';
}

declare module '@windy/BottomSveltePlugins.d' {
  export * from './types/client/BottomSveltePlugins';
}

declare module '@windy/client/BottomSveltePlugins' {
  export * from './types/client/BottomSveltePlugins';
}

declare module '@windy/client/BottomSveltePlugins.d' {
  export * from './types/client/BottomSveltePlugins';
}

declare module '@windy/Calendar' {
  export * from './types/client/Calendar';
}

declare module '@windy/Calendar.d' {
  export * from './types/client/Calendar';
}

declare module '@windy/client/Calendar' {
  export * from './types/client/Calendar';
}

declare module '@windy/client/Calendar.d' {
  export * from './types/client/Calendar';
}

declare module '@windy/CanvasLayer' {
  export * from './types/client/CanvasLayer';
}

declare module '@windy/CanvasLayer.d' {
  export * from './types/client/CanvasLayer';
}

declare module '@windy/client/CanvasLayer' {
  export * from './types/client/CanvasLayer';
}

declare module '@windy/client/CanvasLayer.d' {
  export * from './types/client/CanvasLayer';
}

declare module '@windy/ClickHandler' {
  export * from './types/client/ClickHandler';
}

declare module '@windy/ClickHandler.d' {
  export * from './types/client/ClickHandler';
}

declare module '@windy/client/ClickHandler' {
  export * from './types/client/ClickHandler';
}

declare module '@windy/client/ClickHandler.d' {
  export * from './types/client/ClickHandler';
}

declare module '@windy/Color' {
  export * from './types/client/Color';
}

declare module '@windy/Color.d' {
  export * from './types/client/Color';
}

declare module '@windy/client/Color' {
  export * from './types/client/Color';
}

declare module '@windy/client/Color.d' {
  export * from './types/client/Color';
}

declare module '@windy/DataTiler' {
  export * from './types/client/DataTiler';
}

declare module '@windy/DataTiler.d' {
  export * from './types/client/DataTiler';
}

declare module '@windy/client/DataTiler' {
  export * from './types/client/DataTiler';
}

declare module '@windy/client/DataTiler.d' {
  export * from './types/client/DataTiler';
}

declare module '@windy/Drag' {
  export * from './types/client/Drag';
}

declare module '@windy/Drag.d' {
  export * from './types/client/Drag';
}

declare module '@windy/client/Drag' {
  export * from './types/client/Drag';
}

declare module '@windy/client/Drag.d' {
  export * from './types/client/Drag';
}

declare module '@windy/EcmwfAnalysisProduct' {
  export * from './types/client/EcmwfAnalysisProduct';
}

declare module '@windy/EcmwfAnalysisProduct.d' {
  export * from './types/client/EcmwfAnalysisProduct';
}

declare module '@windy/client/EcmwfAnalysisProduct' {
  export * from './types/client/EcmwfAnalysisProduct';
}

declare module '@windy/client/EcmwfAnalysisProduct.d' {
  export * from './types/client/EcmwfAnalysisProduct';
}

declare module '@windy/EcmwfProduct' {
  export * from './types/client/EcmwfProduct';
}

declare module '@windy/EcmwfProduct.d' {
  export * from './types/client/EcmwfProduct';
}

declare module '@windy/client/EcmwfProduct' {
  export * from './types/client/EcmwfProduct';
}

declare module '@windy/client/EcmwfProduct.d' {
  export * from './types/client/EcmwfProduct';
}

declare module '@windy/EventManager' {
  export * from './types/client/EventManager';
}

declare module '@windy/EventManager.d' {
  export * from './types/client/EventManager';
}

declare module '@windy/client/EventManager' {
  export * from './types/client/EventManager';
}

declare module '@windy/client/EventManager.d' {
  export * from './types/client/EventManager';
}

declare module '@windy/Evented' {
  export * from './types/client/Evented';
}

declare module '@windy/Evented.d' {
  export * from './types/client/Evented';
}

declare module '@windy/client/Evented' {
  export * from './types/client/Evented';
}

declare module '@windy/client/Evented.d' {
  export * from './types/client/Evented';
}

declare module '@windy/ExternalSveltePlugin' {
  export * from './types/client/ExternalSveltePlugin';
}

declare module '@windy/ExternalSveltePlugin.d' {
  export * from './types/client/ExternalSveltePlugin';
}

declare module '@windy/client/ExternalSveltePlugin' {
  export * from './types/client/ExternalSveltePlugin';
}

declare module '@windy/client/ExternalSveltePlugin.d' {
  export * from './types/client/ExternalSveltePlugin';
}

declare module '@windy/GlBuffer' {
  export * from './types/client/GlBuffer';
}

declare module '@windy/GlBuffer.d' {
  export * from './types/client/GlBuffer';
}

declare module '@windy/client/GlBuffer' {
  export * from './types/client/GlBuffer';
}

declare module '@windy/client/GlBuffer.d' {
  export * from './types/client/GlBuffer';
}

declare module '@windy/GlMesh' {
  export * from './types/client/GlMesh';
}

declare module '@windy/GlMesh.d' {
  export * from './types/client/GlMesh';
}

declare module '@windy/client/GlMesh' {
  export * from './types/client/GlMesh';
}

declare module '@windy/client/GlMesh.d' {
  export * from './types/client/GlMesh';
}

declare module '@windy/GlObj' {
  export * from './types/client/GlObj';
  export { default } from './types/client/GlObj';
}

declare module '@windy/GlObj.d' {
  export * from './types/client/GlObj';
  export { default } from './types/client/GlObj';
}

declare module '@windy/client/GlObj' {
  export * from './types/client/GlObj';
  export { default } from './types/client/GlObj';
}

declare module '@windy/client/GlObj.d' {
  export * from './types/client/GlObj';
  export { default } from './types/client/GlObj';
}

declare module '@windy/GlProgram' {
  export * from './types/client/GlProgram';
}

declare module '@windy/GlProgram.d' {
  export * from './types/client/GlProgram';
}

declare module '@windy/client/GlProgram' {
  export * from './types/client/GlProgram';
}

declare module '@windy/client/GlProgram.d' {
  export * from './types/client/GlProgram';
}

declare module '@windy/GlRenderer' {
  export * from './types/client/GlRenderer';
}

declare module '@windy/GlRenderer.d' {
  export * from './types/client/GlRenderer';
}

declare module '@windy/client/GlRenderer' {
  export * from './types/client/GlRenderer';
}

declare module '@windy/client/GlRenderer.d' {
  export * from './types/client/GlRenderer';
}

declare module '@windy/GlTexture' {
  export * from './types/client/GlTexture';
}

declare module '@windy/GlTexture.d' {
  export * from './types/client/GlTexture';
}

declare module '@windy/client/GlTexture' {
  export * from './types/client/GlTexture';
}

declare module '@windy/client/GlTexture.d' {
  export * from './types/client/GlTexture';
}

declare module '@windy/GlVertexArray' {
  export * from './types/client/GlVertexArray';
}

declare module '@windy/GlVertexArray.d' {
  export * from './types/client/GlVertexArray';
}

declare module '@windy/client/GlVertexArray' {
  export * from './types/client/GlVertexArray';
}

declare module '@windy/client/GlVertexArray.d' {
  export * from './types/client/GlVertexArray';
}

declare module '@windy/HrrrProducts' {
  export * from './types/client/HrrrProducts';
}

declare module '@windy/HrrrProducts.d' {
  export * from './types/client/HrrrProducts';
}

declare module '@windy/client/HrrrProducts' {
  export * from './types/client/HrrrProducts';
}

declare module '@windy/client/HrrrProducts.d' {
  export * from './types/client/HrrrProducts';
}

declare module '@windy/IDB' {
  export * from './types/client/IDB';
}

declare module '@windy/IDB.d' {
  export * from './types/client/IDB';
}

declare module '@windy/client/IDB' {
  export * from './types/client/IDB';
}

declare module '@windy/client/IDB.d' {
  export * from './types/client/IDB';
}

declare module '@windy/IconProducts' {
  export * from './types/client/IconProducts';
}

declare module '@windy/IconProducts.d' {
  export * from './types/client/IconProducts';
}

declare module '@windy/client/IconProducts' {
  export * from './types/client/IconProducts';
}

declare module '@windy/client/IconProducts.d' {
  export * from './types/client/IconProducts';
}

declare module '@windy/LabelsLayer' {
  export * from './types/client/LabelsLayer';
  export { default } from './types/client/LabelsLayer';
}

declare module '@windy/LabelsLayer.d' {
  export * from './types/client/LabelsLayer';
  export { default } from './types/client/LabelsLayer';
}

declare module '@windy/client/LabelsLayer' {
  export * from './types/client/LabelsLayer';
  export { default } from './types/client/LabelsLayer';
}

declare module '@windy/client/LabelsLayer.d' {
  export * from './types/client/LabelsLayer';
  export { default } from './types/client/LabelsLayer';
}

declare module '@windy/LandMask' {
  export * from './types/client/LandMask';
  export { default } from './types/client/LandMask';
}

declare module '@windy/LandMask.d' {
  export * from './types/client/LandMask';
  export { default } from './types/client/LandMask';
}

declare module '@windy/client/LandMask' {
  export * from './types/client/LandMask';
  export { default } from './types/client/LandMask';
}

declare module '@windy/client/LandMask.d' {
  export * from './types/client/LandMask';
  export { default } from './types/client/LandMask';
}

declare module '@windy/Layer' {
  export * from './types/client/Layer';
}

declare module '@windy/Layer.d' {
  export * from './types/client/Layer';
}

declare module '@windy/client/Layer' {
  export * from './types/client/Layer';
}

declare module '@windy/client/Layer.d' {
  export * from './types/client/Layer';
}

declare module '@windy/LayerClasses' {
  export * from './types/client/LayerClasses';
}

declare module '@windy/LayerClasses.d' {
  export * from './types/client/LayerClasses';
}

declare module '@windy/client/LayerClasses' {
  export * from './types/client/LayerClasses';
}

declare module '@windy/client/LayerClasses.d' {
  export * from './types/client/LayerClasses';
}

declare module '@windy/Metric' {
  export * from './types/client/Metric';
}

declare module '@windy/Metric.d' {
  export * from './types/client/Metric';
}

declare module '@windy/client/Metric' {
  export * from './types/client/Metric';
}

declare module '@windy/client/Metric.d' {
  export * from './types/client/Metric';
}

declare module '@windy/MetricClasses' {
  export * from './types/client/MetricClasses';
}

declare module '@windy/MetricClasses.d' {
  export * from './types/client/MetricClasses';
}

declare module '@windy/client/MetricClasses' {
  export * from './types/client/MetricClasses';
}

declare module '@windy/client/MetricClasses.d' {
  export * from './types/client/MetricClasses';
}

declare module '@windy/NamProducts' {
  export * from './types/client/NamProducts';
}

declare module '@windy/NamProducts.d' {
  export * from './types/client/NamProducts';
}

declare module '@windy/client/NamProducts' {
  export * from './types/client/NamProducts';
}

declare module '@windy/client/NamProducts.d' {
  export * from './types/client/NamProducts';
}

declare module '@windy/Overlay' {
  export * from './types/client/Overlay';
}

declare module '@windy/Overlay.d' {
  export * from './types/client/Overlay';
}

declare module '@windy/client/Overlay' {
  export * from './types/client/Overlay';
}

declare module '@windy/client/Overlay.d' {
  export * from './types/client/Overlay';
}

declare module '@windy/OverlayClasses' {
  export * from './types/client/OverlayClasses';
}

declare module '@windy/OverlayClasses.d' {
  export * from './types/client/OverlayClasses';
}

declare module '@windy/client/OverlayClasses' {
  export * from './types/client/OverlayClasses';
}

declare module '@windy/client/OverlayClasses.d' {
  export * from './types/client/OverlayClasses';
}

declare module '@windy/Particles' {
  export * from './types/client/Particles';
}

declare module '@windy/Particles.d' {
  export * from './types/client/Particles';
}

declare module '@windy/client/Particles' {
  export * from './types/client/Particles';
}

declare module '@windy/client/Particles.d' {
  export * from './types/client/Particles';
}

declare module '@windy/PatternTranslator' {
  export * from './types/client/PatternTranslator';
}

declare module '@windy/PatternTranslator.d' {
  export * from './types/client/PatternTranslator';
}

declare module '@windy/client/PatternTranslator' {
  export * from './types/client/PatternTranslator';
}

declare module '@windy/client/PatternTranslator.d' {
  export * from './types/client/PatternTranslator';
}

declare module '@windy/Plugin' {
  export * from './types/client/Plugin';
}

declare module '@windy/Plugin.d' {
  export * from './types/client/Plugin';
}

declare module '@windy/client/Plugin' {
  export * from './types/client/Plugin';
}

declare module '@windy/client/Plugin.d' {
  export * from './types/client/Plugin';
}

declare module '@windy/Product' {
  export * from './types/client/Product';
}

declare module '@windy/Product.d' {
  export * from './types/client/Product';
}

declare module '@windy/client/Product' {
  export * from './types/client/Product';
}

declare module '@windy/client/Product.d' {
  export * from './types/client/Product';
}

declare module '@windy/ProductClasses' {
  export * from './types/client/ProductClasses';
}

declare module '@windy/ProductClasses.d' {
  export * from './types/client/ProductClasses';
}

declare module '@windy/client/ProductClasses' {
  export * from './types/client/ProductClasses';
}

declare module '@windy/client/ProductClasses.d' {
  export * from './types/client/ProductClasses';
}

declare module '@windy/RadarPlusProduct' {
  export * from './types/client/RadarPlusProduct';
}

declare module '@windy/RadarPlusProduct.d' {
  export * from './types/client/RadarPlusProduct';
}

declare module '@windy/client/RadarPlusProduct' {
  export * from './types/client/RadarPlusProduct';
}

declare module '@windy/client/RadarPlusProduct.d' {
  export * from './types/client/RadarPlusProduct';
}

declare module '@windy/Renderer' {
  export * from './types/client/Renderer';
}

declare module '@windy/Renderer.d' {
  export * from './types/client/Renderer';
}

declare module '@windy/client/Renderer' {
  export * from './types/client/Renderer';
}

declare module '@windy/client/Renderer.d' {
  export * from './types/client/Renderer';
}

declare module '@windy/SatelliteProduct' {
  export * from './types/client/SatelliteProduct';
}

declare module '@windy/SatelliteProduct.d' {
  export * from './types/client/SatelliteProduct';
}

declare module '@windy/client/SatelliteProduct' {
  export * from './types/client/SatelliteProduct';
}

declare module '@windy/client/SatelliteProduct.d' {
  export * from './types/client/SatelliteProduct';
}

declare module '@windy/ShaderStorage' {
  export * from './types/client/ShaderStorage';
}

declare module '@windy/ShaderStorage.d' {
  export * from './types/client/ShaderStorage';
}

declare module '@windy/client/ShaderStorage' {
  export * from './types/client/ShaderStorage';
}

declare module '@windy/client/ShaderStorage.d' {
  export * from './types/client/ShaderStorage';
}

declare module '@windy/StartupElementPlugin' {
  export * from './types/client/StartupElementPlugin';
}

declare module '@windy/StartupElementPlugin.d' {
  export * from './types/client/StartupElementPlugin';
}

declare module '@windy/client/StartupElementPlugin' {
  export * from './types/client/StartupElementPlugin';
}

declare module '@windy/client/StartupElementPlugin.d' {
  export * from './types/client/StartupElementPlugin';
}

declare module '@windy/StaticProduct' {
  export * from './types/client/StaticProduct';
}

declare module '@windy/StaticProduct.d' {
  export * from './types/client/StaticProduct';
}

declare module '@windy/client/StaticProduct' {
  export * from './types/client/StaticProduct';
}

declare module '@windy/client/StaticProduct.d' {
  export * from './types/client/StaticProduct';
}

declare module '@windy/SveltePanePlugin' {
  export * from './types/client/SveltePanePlugin';
}

declare module '@windy/SveltePanePlugin.d' {
  export * from './types/client/SveltePanePlugin';
}

declare module '@windy/client/SveltePanePlugin' {
  export * from './types/client/SveltePanePlugin';
}

declare module '@windy/client/SveltePanePlugin.d' {
  export * from './types/client/SveltePanePlugin';
}

declare module '@windy/SveltePlugin' {
  export * from './types/client/SveltePlugin';
}

declare module '@windy/SveltePlugin.d' {
  export * from './types/client/SveltePlugin';
}

declare module '@windy/client/SveltePlugin' {
  export * from './types/client/SveltePlugin';
}

declare module '@windy/client/SveltePlugin.d' {
  export * from './types/client/SveltePlugin';
}

declare module '@windy/SveltePopupPlugin' {
  export * from './types/client/SveltePopupPlugin';
}

declare module '@windy/SveltePopupPlugin.d' {
  export * from './types/client/SveltePopupPlugin';
}

declare module '@windy/client/SveltePopupPlugin' {
  export * from './types/client/SveltePopupPlugin';
}

declare module '@windy/client/SveltePopupPlugin.d' {
  export * from './types/client/SveltePopupPlugin';
}

declare module '@windy/Swipe' {
  export * from './types/client/Swipe';
}

declare module '@windy/Swipe.d' {
  export * from './types/client/Swipe';
}

declare module '@windy/client/Swipe' {
  export * from './types/client/Swipe';
}

declare module '@windy/client/Swipe.d' {
  export * from './types/client/Swipe';
}

declare module '@windy/SwitchableTileCache' {
  export * from './types/client/SwitchableTileCache';
}

declare module '@windy/SwitchableTileCache.d' {
  export * from './types/client/SwitchableTileCache';
}

declare module '@windy/client/SwitchableTileCache' {
  export * from './types/client/SwitchableTileCache';
}

declare module '@windy/client/SwitchableTileCache.d' {
  export * from './types/client/SwitchableTileCache';
}

declare module '@windy/TagPlugin' {
  export * from './types/client/TagPlugin';
}

declare module '@windy/TagPlugin.d' {
  export * from './types/client/TagPlugin';
}

declare module '@windy/client/TagPlugin' {
  export * from './types/client/TagPlugin';
}

declare module '@windy/client/TagPlugin.d' {
  export * from './types/client/TagPlugin';
}

declare module '@windy/TileLayer' {
  export * from './types/client/TileLayer';
}

declare module '@windy/TileLayer.d' {
  export * from './types/client/TileLayer';
}

declare module '@windy/client/TileLayer' {
  export * from './types/client/TileLayer';
}

declare module '@windy/client/TileLayer.d' {
  export * from './types/client/TileLayer';
}

declare module '@windy/TileLayerCanvas' {
  export * from './types/client/TileLayerCanvas';
  export { default } from './types/client/TileLayerCanvas';
}

declare module '@windy/TileLayerCanvas.d' {
  export * from './types/client/TileLayerCanvas';
  export { default } from './types/client/TileLayerCanvas';
}

declare module '@windy/client/TileLayerCanvas' {
  export * from './types/client/TileLayerCanvas';
  export { default } from './types/client/TileLayerCanvas';
}

declare module '@windy/client/TileLayerCanvas.d' {
  export * from './types/client/TileLayerCanvas';
  export { default } from './types/client/TileLayerCanvas';
}

declare module '@windy/TileLayerCustom' {
  export * from './types/client/TileLayerCustom';
}

declare module '@windy/TileLayerCustom.d' {
  export * from './types/client/TileLayerCustom';
}

declare module '@windy/client/TileLayerCustom' {
  export * from './types/client/TileLayerCustom';
}

declare module '@windy/client/TileLayerCustom.d' {
  export * from './types/client/TileLayerCustom';
}

declare module '@windy/TileLayerMulti' {
  export * from './types/client/TileLayerMulti';
}

declare module '@windy/TileLayerMulti.d' {
  export * from './types/client/TileLayerMulti';
}

declare module '@windy/client/TileLayerMulti' {
  export * from './types/client/TileLayerMulti';
}

declare module '@windy/client/TileLayerMulti.d' {
  export * from './types/client/TileLayerMulti';
}

declare module '@windy/TileLayerMultiPatch' {
  export * from './types/client/TileLayerMultiPatch';
  export { default } from './types/client/TileLayerMultiPatch';
}

declare module '@windy/TileLayerMultiPatch.d' {
  export * from './types/client/TileLayerMultiPatch';
  export { default } from './types/client/TileLayerMultiPatch';
}

declare module '@windy/client/TileLayerMultiPatch' {
  export * from './types/client/TileLayerMultiPatch';
  export { default } from './types/client/TileLayerMultiPatch';
}

declare module '@windy/client/TileLayerMultiPatch.d' {
  export * from './types/client/TileLayerMultiPatch';
  export { default } from './types/client/TileLayerMultiPatch';
}

declare module '@windy/TileLayerPreprocessorStandalone' {
  export * from './types/client/TileLayerPreprocessorStandalone';
}

declare module '@windy/TileLayerPreprocessorStandalone.d' {
  export * from './types/client/TileLayerPreprocessorStandalone';
}

declare module '@windy/client/TileLayerPreprocessorStandalone' {
  export * from './types/client/TileLayerPreprocessorStandalone';
}

declare module '@windy/client/TileLayerPreprocessorStandalone.d' {
  export * from './types/client/TileLayerPreprocessorStandalone';
}

declare module '@windy/TileLayerRenderer' {
  export * from './types/client/TileLayerRenderer';
}

declare module '@windy/TileLayerRenderer.d' {
  export * from './types/client/TileLayerRenderer';
}

declare module '@windy/client/TileLayerRenderer' {
  export * from './types/client/TileLayerRenderer';
}

declare module '@windy/client/TileLayerRenderer.d' {
  export * from './types/client/TileLayerRenderer';
}

declare module '@windy/TileLayerUtils' {
  export * from './types/client/TileLayerUtils';
}

declare module '@windy/TileLayerUtils.d' {
  export * from './types/client/TileLayerUtils';
}

declare module '@windy/client/TileLayerUtils' {
  export * from './types/client/TileLayerUtils';
}

declare module '@windy/client/TileLayerUtils.d' {
  export * from './types/client/TileLayerUtils';
}

declare module '@windy/TilePreprocessor' {
  export * from './types/client/TilePreprocessor';
}

declare module '@windy/TilePreprocessor.d' {
  export * from './types/client/TilePreprocessor';
}

declare module '@windy/client/TilePreprocessor' {
  export * from './types/client/TilePreprocessor';
}

declare module '@windy/client/TilePreprocessor.d' {
  export * from './types/client/TilePreprocessor';
}

declare module '@windy/TopoMap' {
  export * from './types/client/TopoMap';
}

declare module '@windy/TopoMap.d' {
  export * from './types/client/TopoMap';
}

declare module '@windy/client/TopoMap' {
  export * from './types/client/TopoMap';
}

declare module '@windy/client/TopoMap.d' {
  export * from './types/client/TopoMap';
}

declare module '@windy/Window' {
  export * from './types/client/Window';
}

declare module '@windy/Window.d' {
  export * from './types/client/Window';
}

declare module '@windy/client/Window' {
  export * from './types/client/Window';
}

declare module '@windy/client/Window.d' {
  export * from './types/client/Window';
}

declare module '@windy/WindowPlugin' {
  export * from './types/client/WindowPlugin';
}

declare module '@windy/WindowPlugin.d' {
  export * from './types/client/WindowPlugin';
}

declare module '@windy/client/WindowPlugin' {
  export * from './types/client/WindowPlugin';
}

declare module '@windy/client/WindowPlugin.d' {
  export * from './types/client/WindowPlugin';
}

declare module '@windy/alerts' {
  export * from './types/client/alerts';
}

declare module '@windy/alerts.d' {
  export * from './types/client/alerts';
}

declare module '@windy/client/alerts' {
  export * from './types/client/alerts';
}

declare module '@windy/client/alerts.d' {
  export * from './types/client/alerts';
}

declare module '@windy/alerts.test' {
  export * from './types/client/alerts.test';
}

declare module '@windy/alerts.test.d' {
  export * from './types/client/alerts.test';
}

declare module '@windy/client/alerts.test' {
  export * from './types/client/alerts.test';
}

declare module '@windy/client/alerts.test.d' {
  export * from './types/client/alerts.test';
}

declare module '@windy/alternativeLegends' {
  export * from './types/client/alternativeLegends';
}

declare module '@windy/alternativeLegends.d' {
  export * from './types/client/alternativeLegends';
}

declare module '@windy/client/alternativeLegends' {
  export * from './types/client/alternativeLegends';
}

declare module '@windy/client/alternativeLegends.d' {
  export * from './types/client/alternativeLegends';
}

declare module '@windy/appsFlyer' {
  export * from './types/client/appsFlyer';
}

declare module '@windy/appsFlyer.d' {
  export * from './types/client/appsFlyer';
}

declare module '@windy/client/appsFlyer' {
  export * from './types/client/appsFlyer';
}

declare module '@windy/client/appsFlyer.d' {
  export * from './types/client/appsFlyer';
}

declare module '@windy/baseMap' {
  export * from './types/client/baseMap';
}

declare module '@windy/baseMap.d' {
  export * from './types/client/baseMap';
}

declare module '@windy/client/baseMap' {
  export * from './types/client/baseMap';
}

declare module '@windy/client/baseMap.d' {
  export * from './types/client/baseMap';
}

declare module '@windy/broadcast' {
  export * from './types/client/broadcast';
  export { default } from './types/client/broadcast';
}

declare module '@windy/broadcast.d' {
  export * from './types/client/broadcast';
  export { default } from './types/client/broadcast';
}

declare module '@windy/client/broadcast' {
  export * from './types/client/broadcast';
  export { default } from './types/client/broadcast';
}

declare module '@windy/client/broadcast.d' {
  export * from './types/client/broadcast';
  export { default } from './types/client/broadcast';
}

declare module '@windy/cityLabels' {
  export * from './types/client/cityLabels';
}

declare module '@windy/cityLabels.d' {
  export * from './types/client/cityLabels';
}

declare module '@windy/client/cityLabels' {
  export * from './types/client/cityLabels';
}

declare module '@windy/client/cityLabels.d' {
  export * from './types/client/cityLabels';
}

declare module '@windy/cloudSync' {
  export * from './types/client/cloudSync';
}

declare module '@windy/cloudSync.d' {
  export * from './types/client/cloudSync';
}

declare module '@windy/client/cloudSync' {
  export * from './types/client/cloudSync';
}

declare module '@windy/client/cloudSync.d' {
  export * from './types/client/cloudSync';
}

declare module '@windy/colorGradients' {
  export * from './types/client/colorGradients';
}

declare module '@windy/colorGradients.d' {
  export * from './types/client/colorGradients';
}

declare module '@windy/client/colorGradients' {
  export * from './types/client/colorGradients';
}

declare module '@windy/client/colorGradients.d' {
  export * from './types/client/colorGradients';
}

declare module '@windy/colors' {
  export * from './types/client/colors';
  export { default } from './types/client/colors';
}

declare module '@windy/colors.d' {
  export * from './types/client/colors';
  export { default } from './types/client/colors';
}

declare module '@windy/client/colors' {
  export * from './types/client/colors';
  export { default } from './types/client/colors';
}

declare module '@windy/client/colors.d' {
  export * from './types/client/colors';
  export { default } from './types/client/colors';
}

declare module '@windy/commonExports' {
  export * from './types/client/commonExports';
  export { default } from './types/client/commonExports';
}

declare module '@windy/commonExports.d' {
  export * from './types/client/commonExports';
  export { default } from './types/client/commonExports';
}

declare module '@windy/client/commonExports' {
  export * from './types/client/commonExports';
  export { default } from './types/client/commonExports';
}

declare module '@windy/client/commonExports.d' {
  export * from './types/client/commonExports';
  export { default } from './types/client/commonExports';
}

declare module '@windy/compatibilityCheck' {
  export * from './types/client/compatibilityCheck';
}

declare module '@windy/compatibilityCheck.d' {
  export * from './types/client/compatibilityCheck';
}

declare module '@windy/client/compatibilityCheck' {
  export * from './types/client/compatibilityCheck';
}

declare module '@windy/client/compatibilityCheck.d' {
  export * from './types/client/compatibilityCheck';
}

declare module '@windy/components' {
  export * from './types/client/components';
}

declare module '@windy/components.d' {
  export * from './types/client/components';
}

declare module '@windy/client/components' {
  export * from './types/client/components';
}

declare module '@windy/client/components.d' {
  export * from './types/client/components';
}

declare module '@windy/connection' {
  export * from './types/client/connection';
}

declare module '@windy/connection.d' {
  export * from './types/client/connection';
}

declare module '@windy/client/connection' {
  export * from './types/client/connection';
}

declare module '@windy/client/connection.d' {
  export * from './types/client/connection';
}

declare module '@windy/css' {
  export * from './types/client/css';
}

declare module '@windy/css.d' {
  export * from './types/client/css';
}

declare module '@windy/client/css' {
  export * from './types/client/css';
}

declare module '@windy/client/css.d' {
  export * from './types/client/css';
}

declare module '@windy/css.test' {
  export * from './types/client/css.test';
}

declare module '@windy/css.test.d' {
  export * from './types/client/css.test';
}

declare module '@windy/client/css.test' {
  export * from './types/client/css.test';
}

declare module '@windy/client/css.test.d' {
  export * from './types/client/css.test';
}

declare module '@windy/customColors' {
  export * from './types/client/customColors';
}

declare module '@windy/customColors.d' {
  export * from './types/client/customColors';
}

declare module '@windy/client/customColors' {
  export * from './types/client/customColors';
}

declare module '@windy/client/customColors.d' {
  export * from './types/client/customColors';
}

declare module '@windy/customProtocol' {
  export * from './types/client/customProtocol';
}

declare module '@windy/customProtocol.d' {
  export * from './types/client/customProtocol';
}

declare module '@windy/client/customProtocol' {
  export * from './types/client/customProtocol';
}

declare module '@windy/client/customProtocol.d' {
  export * from './types/client/customProtocol';
}

declare module '@windy/dataLoader' {
  export * from './types/client/dataLoader';
}

declare module '@windy/dataLoader.d' {
  export * from './types/client/dataLoader';
}

declare module '@windy/client/dataLoader' {
  export * from './types/client/dataLoader';
}

declare module '@windy/client/dataLoader.d' {
  export * from './types/client/dataLoader';
}

declare module '@windy/dataSpecifications' {
  export * from './types/client/dataSpecifications';
  export { default } from './types/client/dataSpecifications';
}

declare module '@windy/dataSpecifications.d' {
  export * from './types/client/dataSpecifications';
  export { default } from './types/client/dataSpecifications';
}

declare module '@windy/client/dataSpecifications' {
  export * from './types/client/dataSpecifications';
  export { default } from './types/client/dataSpecifications';
}

declare module '@windy/client/dataSpecifications.d' {
  export * from './types/client/dataSpecifications';
  export { default } from './types/client/dataSpecifications';
}

declare module '@windy/debugPremiumIssues' {
  export * from './types/client/debugPremiumIssues';
  export { default } from './types/client/debugPremiumIssues';
}

declare module '@windy/debugPremiumIssues.d' {
  export * from './types/client/debugPremiumIssues';
  export { default } from './types/client/debugPremiumIssues';
}

declare module '@windy/client/debugPremiumIssues' {
  export * from './types/client/debugPremiumIssues';
  export { default } from './types/client/debugPremiumIssues';
}

declare module '@windy/client/debugPremiumIssues.d' {
  export * from './types/client/debugPremiumIssues';
  export { default } from './types/client/debugPremiumIssues';
}

declare module '@windy/detectDevice' {
  export * from './types/client/detectDevice';
}

declare module '@windy/detectDevice.d' {
  export * from './types/client/detectDevice';
}

declare module '@windy/client/detectDevice' {
  export * from './types/client/detectDevice';
}

declare module '@windy/client/detectDevice.d' {
  export * from './types/client/detectDevice';
}

declare module '@windy/device' {
  export * from './types/client/device';
}

declare module '@windy/device.d' {
  export * from './types/client/device';
}

declare module '@windy/client/device' {
  export * from './types/client/device';
}

declare module '@windy/client/device.d' {
  export * from './types/client/device';
}

declare module '@windy/deviceLogging' {
  export * from './types/client/deviceLogging';
}

declare module '@windy/deviceLogging.d' {
  export * from './types/client/deviceLogging';
}

declare module '@windy/client/deviceLogging' {
  export * from './types/client/deviceLogging';
}

declare module '@windy/client/deviceLogging.d' {
  export * from './types/client/deviceLogging';
}

declare module '@windy/embed' {
  export * from './types/client/embed';
  export { default } from './types/client/embed';
}

declare module '@windy/embed.d' {
  export * from './types/client/embed';
  export { default } from './types/client/embed';
}

declare module '@windy/client/embed' {
  export * from './types/client/embed';
  export { default } from './types/client/embed';
}

declare module '@windy/client/embed.d' {
  export * from './types/client/embed';
  export { default } from './types/client/embed';
}

declare module '@windy/embed2' {
  export * from './types/client/embed2';
  export { default } from './types/client/embed2';
}

declare module '@windy/embed2.d' {
  export * from './types/client/embed2';
  export { default } from './types/client/embed2';
}

declare module '@windy/client/embed2' {
  export * from './types/client/embed2';
  export { default } from './types/client/embed2';
}

declare module '@windy/client/embed2.d' {
  export * from './types/client/embed2';
  export { default } from './types/client/embed2';
}

declare module '@windy/errorLogger' {
  export * from './types/client/errorLogger';
}

declare module '@windy/errorLogger.d' {
  export * from './types/client/errorLogger';
}

declare module '@windy/client/errorLogger' {
  export * from './types/client/errorLogger';
}

declare module '@windy/client/errorLogger.d' {
  export * from './types/client/errorLogger';
}

declare module '@windy/errors' {
  export * from './types/client/errors';
}

declare module '@windy/errors.d' {
  export * from './types/client/errors';
}

declare module '@windy/client/errors' {
  export * from './types/client/errors';
}

declare module '@windy/client/errors.d' {
  export * from './types/client/errors';
}

declare module '@windy/externalPlugins' {
  export * from './types/client/externalPlugins';
}

declare module '@windy/externalPlugins.d' {
  export * from './types/client/externalPlugins';
}

declare module '@windy/client/externalPlugins' {
  export * from './types/client/externalPlugins';
}

declare module '@windy/client/externalPlugins.d' {
  export * from './types/client/externalPlugins';
}

declare module '@windy/fetch' {
  export * from './types/client/fetch';
}

declare module '@windy/fetch.d' {
  export * from './types/client/fetch';
}

declare module '@windy/client/fetch' {
  export * from './types/client/fetch';
}

declare module '@windy/client/fetch.d' {
  export * from './types/client/fetch';
}

declare module '@windy/fetchForecastHosts' {
  export * from './types/client/fetchForecastHosts';
}

declare module '@windy/fetchForecastHosts.d' {
  export * from './types/client/fetchForecastHosts';
}

declare module '@windy/client/fetchForecastHosts' {
  export * from './types/client/fetchForecastHosts';
}

declare module '@windy/client/fetchForecastHosts.d' {
  export * from './types/client/fetchForecastHosts';
}

declare module '@windy/fetchWebcamsHosts' {
  export * from './types/client/fetchWebcamsHosts';
}

declare module '@windy/fetchWebcamsHosts.d' {
  export * from './types/client/fetchWebcamsHosts';
}

declare module '@windy/client/fetchWebcamsHosts' {
  export * from './types/client/fetchWebcamsHosts';
}

declare module '@windy/client/fetchWebcamsHosts.d' {
  export * from './types/client/fetchWebcamsHosts';
}

declare module '@windy/format' {
  export * from './types/client/format';
}

declare module '@windy/format.d' {
  export * from './types/client/format';
}

declare module '@windy/client/format' {
  export * from './types/client/format';
}

declare module '@windy/client/format.d' {
  export * from './types/client/format';
}

declare module '@windy/ga' {
  export * from './types/client/ga';
}

declare module '@windy/ga.d' {
  export * from './types/client/ga';
}

declare module '@windy/client/ga' {
  export * from './types/client/ga';
}

declare module '@windy/client/ga.d' {
  export * from './types/client/ga';
}

declare module '@windy/geolocation' {
  export * from './types/client/geolocation';
}

declare module '@windy/geolocation.d' {
  export * from './types/client/geolocation';
}

declare module '@windy/client/geolocation' {
  export * from './types/client/geolocation';
}

declare module '@windy/client/geolocation.d' {
  export * from './types/client/geolocation';
}

declare module '@windy/glContextUtils' {
  export * from './types/client/glContextUtils';
}

declare module '@windy/glContextUtils.d' {
  export * from './types/client/glContextUtils';
}

declare module '@windy/client/glContextUtils' {
  export * from './types/client/glContextUtils';
}

declare module '@windy/client/glContextUtils.d' {
  export * from './types/client/glContextUtils';
}

declare module '@windy/glStatus' {
  export * from './types/client/glStatus';
}

declare module '@windy/glStatus.d' {
  export * from './types/client/glStatus';
}

declare module '@windy/client/glStatus' {
  export * from './types/client/glStatus';
}

declare module '@windy/client/glStatus.d' {
  export * from './types/client/glStatus';
}

declare module '@windy/glTileRender' {
  export * from './types/client/glTileRender';
  export { default } from './types/client/glTileRender';
}

declare module '@windy/glTileRender.d' {
  export * from './types/client/glTileRender';
  export { default } from './types/client/glTileRender';
}

declare module '@windy/client/glTileRender' {
  export * from './types/client/glTileRender';
  export { default } from './types/client/glTileRender';
}

declare module '@windy/client/glTileRender.d' {
  export * from './types/client/glTileRender';
  export { default } from './types/client/glTileRender';
}

declare module '@windy/glUtils' {
  export * from './types/client/glUtils';
}

declare module '@windy/glUtils.d' {
  export * from './types/client/glUtils';
}

declare module '@windy/client/glUtils' {
  export * from './types/client/glUtils';
}

declare module '@windy/client/glUtils.d' {
  export * from './types/client/glUtils';
}

declare module '@windy/globals' {
  export * from './types/client/globals';
}

declare module '@windy/globals.d' {
  export * from './types/client/globals';
}

declare module '@windy/client/globals' {
  export * from './types/client/globals';
}

declare module '@windy/client/globals.d' {
  export * from './types/client/globals';
}

declare module '@windy/http' {
  export * from './types/client/http';
}

declare module '@windy/http.d' {
  export * from './types/client/http';
}

declare module '@windy/client/http' {
  export * from './types/client/http';
}

declare module '@windy/client/http.d' {
  export * from './types/client/http';
}

declare module '@windy/idbConnection' {
  export * from './types/client/idbConnection';
}

declare module '@windy/idbConnection.d' {
  export * from './types/client/idbConnection';
}

declare module '@windy/client/idbConnection' {
  export * from './types/client/idbConnection';
}

declare module '@windy/client/idbConnection.d' {
  export * from './types/client/idbConnection';
}

declare module '@windy/idbInstances' {
  export * from './types/client/idbInstances';
}

declare module '@windy/idbInstances.d' {
  export * from './types/client/idbInstances';
}

declare module '@windy/client/idbInstances' {
  export * from './types/client/idbInstances';
}

declare module '@windy/client/idbInstances.d' {
  export * from './types/client/idbInstances';
}

declare module '@windy/imakerMain' {
  export * from './types/client/imakerMain';
}

declare module '@windy/imakerMain.d' {
  export * from './types/client/imakerMain';
}

declare module '@windy/client/imakerMain' {
  export * from './types/client/imakerMain';
}

declare module '@windy/client/imakerMain.d' {
  export * from './types/client/imakerMain';
}

declare module '@windy/index' {
  export * from './types/client/index';
}

declare module '@windy/index.d' {
  export * from './types/client/index';
}

declare module '@windy/client/index' {
  export * from './types/client/index';
}

declare module '@windy/client/index.d' {
  export * from './types/client/index';
}

declare module '@windy/interpolator' {
  export * from './types/client/interpolator';
}

declare module '@windy/interpolator.d' {
  export * from './types/client/interpolator';
}

declare module '@windy/client/interpolator' {
  export * from './types/client/interpolator';
}

declare module '@windy/client/interpolator.d' {
  export * from './types/client/interpolator';
}

declare module '@windy/keyboard' {
  export * from './types/client/keyboard';
}

declare module '@windy/keyboard.d' {
  export * from './types/client/keyboard';
}

declare module '@windy/client/keyboard' {
  export * from './types/client/keyboard';
}

declare module '@windy/client/keyboard.d' {
  export * from './types/client/keyboard';
}

declare module '@windy/landLayer' {
  export * from './types/client/landLayer';
}

declare module '@windy/landLayer.d' {
  export * from './types/client/landLayer';
}

declare module '@windy/client/landLayer' {
  export * from './types/client/landLayer';
}

declare module '@windy/client/landLayer.d' {
  export * from './types/client/landLayer';
}

declare module '@windy/langFiles' {
  export * from './types/client/langFiles';
  export { default } from './types/client/langFiles';
}

declare module '@windy/langFiles.d' {
  export * from './types/client/langFiles';
  export { default } from './types/client/langFiles';
}

declare module '@windy/client/langFiles' {
  export * from './types/client/langFiles';
  export { default } from './types/client/langFiles';
}

declare module '@windy/client/langFiles.d' {
  export * from './types/client/langFiles';
  export { default } from './types/client/langFiles';
}

declare module '@windy/latestBroadcasts' {
  export * from './types/client/latestBroadcasts';
}

declare module '@windy/latestBroadcasts.d' {
  export * from './types/client/latestBroadcasts';
}

declare module '@windy/client/latestBroadcasts' {
  export * from './types/client/latestBroadcasts';
}

declare module '@windy/client/latestBroadcasts.d' {
  export * from './types/client/latestBroadcasts';
}

declare module '@windy/layers' {
  export * from './types/client/layers';
  export { default } from './types/client/layers';
}

declare module '@windy/layers.d' {
  export * from './types/client/layers';
  export { default } from './types/client/layers';
}

declare module '@windy/client/layers' {
  export * from './types/client/layers';
  export { default } from './types/client/layers';
}

declare module '@windy/client/layers.d' {
  export * from './types/client/layers';
  export { default } from './types/client/layers';
}

declare module '@windy/legends' {
  export * from './types/client/legends';
  export { default } from './types/client/legends';
}

declare module '@windy/legends.d' {
  export * from './types/client/legends';
  export { default } from './types/client/legends';
}

declare module '@windy/client/legends' {
  export * from './types/client/legends';
  export { default } from './types/client/legends';
}

declare module '@windy/client/legends.d' {
  export * from './types/client/legends';
  export { default } from './types/client/legends';
}

declare module '@windy/levelUtils' {
  export * from './types/client/levelUtils';
}

declare module '@windy/levelUtils.d' {
  export * from './types/client/levelUtils';
}

declare module '@windy/client/levelUtils' {
  export * from './types/client/levelUtils';
}

declare module '@windy/client/levelUtils.d' {
  export * from './types/client/levelUtils';
}

declare module '@windy/lib' {
  export * from './types/client/lib';
  export { default } from './types/client/lib';
}

declare module '@windy/lib.d' {
  export * from './types/client/lib';
  export { default } from './types/client/lib';
}

declare module '@windy/client/lib' {
  export * from './types/client/lib';
  export { default } from './types/client/lib';
}

declare module '@windy/client/lib.d' {
  export * from './types/client/lib';
  export { default } from './types/client/lib';
}

declare module '@windy/libGuard' {
  export * from './types/client/libGuard';
}

declare module '@windy/libGuard.d' {
  export * from './types/client/libGuard';
}

declare module '@windy/client/libGuard' {
  export * from './types/client/libGuard';
}

declare module '@windy/client/libGuard.d' {
  export * from './types/client/libGuard';
}

declare module '@windy/libHtml' {
  export * from './types/client/libHtml';
  export { default } from './types/client/libHtml';
}

declare module '@windy/libHtml.d' {
  export * from './types/client/libHtml';
  export { default } from './types/client/libHtml';
}

declare module '@windy/client/libHtml' {
  export * from './types/client/libHtml';
  export { default } from './types/client/libHtml';
}

declare module '@windy/client/libHtml.d' {
  export * from './types/client/libHtml';
  export { default } from './types/client/libHtml';
}

declare module '@windy/liveAlerts' {
  export * from './types/client/liveAlerts';
}

declare module '@windy/liveAlerts.d' {
  export * from './types/client/liveAlerts';
}

declare module '@windy/client/liveAlerts' {
  export * from './types/client/liveAlerts';
}

declare module '@windy/client/liveAlerts.d' {
  export * from './types/client/liveAlerts';
}

declare module '@windy/liveAlerts.types' {
  export * from './types/client/liveAlerts.types';
}

declare module '@windy/liveAlerts.types.d' {
  export * from './types/client/liveAlerts.types';
}

declare module '@windy/client/liveAlerts.types' {
  export * from './types/client/liveAlerts.types';
}

declare module '@windy/client/liveAlerts.types.d' {
  export * from './types/client/liveAlerts.types';
}

declare module '@windy/loadArticlesOrWhatsNew' {
  export * from './types/client/loadArticlesOrWhatsNew';
}

declare module '@windy/loadArticlesOrWhatsNew.d' {
  export * from './types/client/loadArticlesOrWhatsNew';
}

declare module '@windy/client/loadArticlesOrWhatsNew' {
  export * from './types/client/loadArticlesOrWhatsNew';
}

declare module '@windy/client/loadArticlesOrWhatsNew.d' {
  export * from './types/client/loadArticlesOrWhatsNew';
}

declare module '@windy/location' {
  export * from './types/client/location';
}

declare module '@windy/location.d' {
  export * from './types/client/location';
}

declare module '@windy/client/location' {
  export * from './types/client/location';
}

declare module '@windy/client/location.d' {
  export * from './types/client/location';
}

declare module '@windy/log' {
  export * from './types/client/log';
}

declare module '@windy/log.d' {
  export * from './types/client/log';
}

declare module '@windy/client/log' {
  export * from './types/client/log';
}

declare module '@windy/client/log.d' {
  export * from './types/client/log';
}

declare module '@windy/lruCache' {
  export * from './types/client/lruCache';
  export { default } from './types/client/lruCache';
}

declare module '@windy/lruCache.d' {
  export * from './types/client/lruCache';
  export { default } from './types/client/lruCache';
}

declare module '@windy/client/lruCache' {
  export * from './types/client/lruCache';
  export { default } from './types/client/lruCache';
}

declare module '@windy/client/lruCache.d' {
  export * from './types/client/lruCache';
  export { default } from './types/client/lruCache';
}

declare module '@windy/map' {
  export * from './types/client/map';
}

declare module '@windy/map.d' {
  export * from './types/client/map';
}

declare module '@windy/client/map' {
  export * from './types/client/map';
}

declare module '@windy/client/map.d' {
  export * from './types/client/map';
}

declare module '@windy/mapGlobeCtrl' {
  export * from './types/client/mapGlobeCtrl';
}

declare module '@windy/mapGlobeCtrl.d' {
  export * from './types/client/mapGlobeCtrl';
}

declare module '@windy/client/mapGlobeCtrl' {
  export * from './types/client/mapGlobeCtrl';
}

declare module '@windy/client/mapGlobeCtrl.d' {
  export * from './types/client/mapGlobeCtrl';
}

declare module '@windy/mapUtils' {
  export * from './types/client/mapUtils';
}

declare module '@windy/mapUtils.d' {
  export * from './types/client/mapUtils';
}

declare module '@windy/client/mapUtils' {
  export * from './types/client/mapUtils';
}

declare module '@windy/client/mapUtils.d' {
  export * from './types/client/mapUtils';
}

declare module '@windy/math' {
  export * from './types/client/math';
}

declare module '@windy/math.d' {
  export * from './types/client/math';
}

declare module '@windy/client/math' {
  export * from './types/client/math';
}

declare module '@windy/client/math.d' {
  export * from './types/client/math';
}

declare module '@windy/metrics' {
  export * from './types/client/metrics';
  export { default } from './types/client/metrics';
}

declare module '@windy/metrics.d' {
  export * from './types/client/metrics';
  export { default } from './types/client/metrics';
}

declare module '@windy/client/metrics' {
  export * from './types/client/metrics';
  export { default } from './types/client/metrics';
}

declare module '@windy/client/metrics.d' {
  export * from './types/client/metrics';
  export { default } from './types/client/metrics';
}

declare module '@windy/mobile' {
  export * from './types/client/mobile';
}

declare module '@windy/mobile.d' {
  export * from './types/client/mobile';
}

declare module '@windy/client/mobile' {
  export * from './types/client/mobile';
}

declare module '@windy/client/mobile.d' {
  export * from './types/client/mobile';
}

declare module '@windy/mobileUtils' {
  export * from './types/client/mobileUtils';
}

declare module '@windy/mobileUtils.d' {
  export * from './types/client/mobileUtils';
}

declare module '@windy/client/mobileUtils' {
  export * from './types/client/mobileUtils';
}

declare module '@windy/client/mobileUtils.d' {
  export * from './types/client/mobileUtils';
}

declare module '@windy/models' {
  export * from './types/client/models';
}

declare module '@windy/models.d' {
  export * from './types/client/models';
}

declare module '@windy/client/models' {
  export * from './types/client/models';
}

declare module '@windy/client/models.d' {
  export * from './types/client/models';
}

declare module '@windy/nativeStorage' {
  export * from './types/client/nativeStorage';
}

declare module '@windy/nativeStorage.d' {
  export * from './types/client/nativeStorage';
}

declare module '@windy/client/nativeStorage' {
  export * from './types/client/nativeStorage';
}

declare module '@windy/client/nativeStorage.d' {
  export * from './types/client/nativeStorage';
}

declare module '@windy/notifications' {
  export * from './types/client/notifications';
}

declare module '@windy/notifications.d' {
  export * from './types/client/notifications';
}

declare module '@windy/client/notifications' {
  export * from './types/client/notifications';
}

declare module '@windy/client/notifications.d' {
  export * from './types/client/notifications';
}

declare module '@windy/ogTags' {
  export * from './types/client/ogTags';
}

declare module '@windy/ogTags.d' {
  export * from './types/client/ogTags';
}

declare module '@windy/client/ogTags' {
  export * from './types/client/ogTags';
}

declare module '@windy/client/ogTags.d' {
  export * from './types/client/ogTags';
}

declare module '@windy/overlays' {
  export * from './types/client/overlays';
  export { default } from './types/client/overlays';
}

declare module '@windy/overlays.d' {
  export * from './types/client/overlays';
  export { default } from './types/client/overlays';
}

declare module '@windy/client/overlays' {
  export * from './types/client/overlays';
  export { default } from './types/client/overlays';
}

declare module '@windy/client/overlays.d' {
  export * from './types/client/overlays';
  export { default } from './types/client/overlays';
}

declare module '@windy/params' {
  export * from './types/client/params';
}

declare module '@windy/params.d' {
  export * from './types/client/params';
}

declare module '@windy/client/params' {
  export * from './types/client/params';
}

declare module '@windy/client/params.d' {
  export * from './types/client/params';
}

declare module '@windy/particleRenderers' {
  export * from './types/client/particleRenderers';
  export { default } from './types/client/particleRenderers';
}

declare module '@windy/particleRenderers.d' {
  export * from './types/client/particleRenderers';
  export { default } from './types/client/particleRenderers';
}

declare module '@windy/client/particleRenderers' {
  export * from './types/client/particleRenderers';
  export { default } from './types/client/particleRenderers';
}

declare module '@windy/client/particleRenderers.d' {
  export * from './types/client/particleRenderers';
  export { default } from './types/client/particleRenderers';
}

declare module '@windy/patchAndPromoCtrl' {
  export * from './types/client/patchAndPromoCtrl';
}

declare module '@windy/patchAndPromoCtrl.d' {
  export * from './types/client/patchAndPromoCtrl';
}

declare module '@windy/client/patchAndPromoCtrl' {
  export * from './types/client/patchAndPromoCtrl';
}

declare module '@windy/client/patchAndPromoCtrl.d' {
  export * from './types/client/patchAndPromoCtrl';
}

declare module '@windy/permanentPromos' {
  export * from './types/client/permanentPromos';
}

declare module '@windy/permanentPromos.d' {
  export * from './types/client/permanentPromos';
}

declare module '@windy/client/permanentPromos' {
  export * from './types/client/permanentPromos';
}

declare module '@windy/client/permanentPromos.d' {
  export * from './types/client/permanentPromos';
}

declare module '@windy/persistentStorage' {
  export * from './types/client/persistentStorage';
}

declare module '@windy/persistentStorage.d' {
  export * from './types/client/persistentStorage';
}

declare module '@windy/client/persistentStorage' {
  export * from './types/client/persistentStorage';
}

declare module '@windy/client/persistentStorage.d' {
  export * from './types/client/persistentStorage';
}

declare module '@windy/picker' {
  export * from './types/client/picker';
}

declare module '@windy/picker.d' {
  export * from './types/client/picker';
}

declare module '@windy/client/picker' {
  export * from './types/client/picker';
}

declare module '@windy/client/picker.d' {
  export * from './types/client/picker';
}

declare module '@windy/pixelReader' {
  export * from './types/client/pixelReader';
}

declare module '@windy/pixelReader.d' {
  export * from './types/client/pixelReader';
}

declare module '@windy/client/pixelReader' {
  export * from './types/client/pixelReader';
}

declare module '@windy/client/pixelReader.d' {
  export * from './types/client/pixelReader';
}

declare module '@windy/plugins' {
  export * from './types/client/plugins';
  export { default } from './types/client/plugins';
}

declare module '@windy/plugins.d' {
  export * from './types/client/plugins';
  export { default } from './types/client/plugins';
}

declare module '@windy/client/plugins' {
  export * from './types/client/plugins';
  export { default } from './types/client/plugins';
}

declare module '@windy/client/plugins.d' {
  export * from './types/client/plugins';
  export { default } from './types/client/plugins';
}

declare module '@windy/pluginsCtrl' {
  export * from './types/client/pluginsCtrl';
}

declare module '@windy/pluginsCtrl.d' {
  export * from './types/client/pluginsCtrl';
}

declare module '@windy/client/pluginsCtrl' {
  export * from './types/client/pluginsCtrl';
}

declare module '@windy/client/pluginsCtrl.d' {
  export * from './types/client/pluginsCtrl';
}

declare module '@windy/pois' {
  export * from './types/client/pois';
}

declare module '@windy/pois.d' {
  export * from './types/client/pois';
}

declare module '@windy/client/pois' {
  export * from './types/client/pois';
}

declare module '@windy/client/pois.d' {
  export * from './types/client/pois';
}

declare module '@windy/products' {
  export * from './types/client/products';
  export { default } from './types/client/products';
}

declare module '@windy/products.d' {
  export * from './types/client/products';
  export { default } from './types/client/products';
}

declare module '@windy/client/products' {
  export * from './types/client/products';
  export { default } from './types/client/products';
}

declare module '@windy/client/products.d' {
  export * from './types/client/products';
  export { default } from './types/client/products';
}

declare module '@windy/promo' {
  export * from './types/client/promo';
}

declare module '@windy/promo.d' {
  export * from './types/client/promo';
}

declare module '@windy/client/promo' {
  export * from './types/client/promo';
}

declare module '@windy/client/promo.d' {
  export * from './types/client/promo';
}

declare module '@windy/pushNotifications' {
  export * from './types/client/pushNotifications';
}

declare module '@windy/pushNotifications.d' {
  export * from './types/client/pushNotifications';
}

declare module '@windy/client/pushNotifications' {
  export * from './types/client/pushNotifications';
}

declare module '@windy/client/pushNotifications.d' {
  export * from './types/client/pushNotifications';
}

declare module '@windy/query' {
  export * from './types/client/query';
}

declare module '@windy/query.d' {
  export * from './types/client/query';
}

declare module '@windy/client/query' {
  export * from './types/client/query';
}

declare module '@windy/client/query.d' {
  export * from './types/client/query';
}

declare module '@windy/queryString' {
  export * from './types/client/queryString';
}

declare module '@windy/queryString.d' {
  export * from './types/client/queryString';
}

declare module '@windy/client/queryString' {
  export * from './types/client/queryString';
}

declare module '@windy/client/queryString.d' {
  export * from './types/client/queryString';
}

declare module '@windy/queue' {
  export * from './types/client/queue';
}

declare module '@windy/queue.d' {
  export * from './types/client/queue';
}

declare module '@windy/client/queue' {
  export * from './types/client/queue';
}

declare module '@windy/client/queue.d' {
  export * from './types/client/queue';
}

declare module '@windy/renderCtrl' {
  export * from './types/client/renderCtrl';
}

declare module '@windy/renderCtrl.d' {
  export * from './types/client/renderCtrl';
}

declare module '@windy/client/renderCtrl' {
  export * from './types/client/renderCtrl';
}

declare module '@windy/client/renderCtrl.d' {
  export * from './types/client/renderCtrl';
}

declare module '@windy/renderLegend' {
  export * from './types/client/renderLegend';
}

declare module '@windy/renderLegend.d' {
  export * from './types/client/renderLegend';
}

declare module '@windy/client/renderLegend' {
  export * from './types/client/renderLegend';
}

declare module '@windy/client/renderLegend.d' {
  export * from './types/client/renderLegend';
}

declare module '@windy/renderTile' {
  export * from './types/client/renderTile';
}

declare module '@windy/renderTile.d' {
  export * from './types/client/renderTile';
}

declare module '@windy/client/renderTile' {
  export * from './types/client/renderTile';
}

declare module '@windy/client/renderTile.d' {
  export * from './types/client/renderTile';
}

declare module '@windy/renderUtils' {
  export * from './types/client/renderUtils';
}

declare module '@windy/renderUtils.d' {
  export * from './types/client/renderUtils';
}

declare module '@windy/client/renderUtils' {
  export * from './types/client/renderUtils';
}

declare module '@windy/client/renderUtils.d' {
  export * from './types/client/renderUtils';
}

declare module '@windy/renderers' {
  export * from './types/client/renderers';
  export { default } from './types/client/renderers';
}

declare module '@windy/renderers.d' {
  export * from './types/client/renderers';
  export { default } from './types/client/renderers';
}

declare module '@windy/client/renderers' {
  export * from './types/client/renderers';
  export { default } from './types/client/renderers';
}

declare module '@windy/client/renderers.d' {
  export * from './types/client/renderers';
  export { default } from './types/client/renderers';
}

declare module '@windy/reverseName' {
  export * from './types/client/reverseName';
}

declare module '@windy/reverseName.d' {
  export * from './types/client/reverseName';
}

declare module '@windy/client/reverseName' {
  export * from './types/client/reverseName';
}

declare module '@windy/client/reverseName.d' {
  export * from './types/client/reverseName';
}

declare module '@windy/rhMessage' {
  export * from './types/client/rhMessage';
}

declare module '@windy/rhMessage.d' {
  export * from './types/client/rhMessage';
}

declare module '@windy/client/rhMessage' {
  export * from './types/client/rhMessage';
}

declare module '@windy/client/rhMessage.d' {
  export * from './types/client/rhMessage';
}

declare module '@windy/rootScope' {
  export * from './types/client/rootScope';
}

declare module '@windy/rootScope.d' {
  export * from './types/client/rootScope';
}

declare module '@windy/client/rootScope' {
  export * from './types/client/rootScope';
}

declare module '@windy/client/rootScope.d' {
  export * from './types/client/rootScope';
}

declare module '@windy/router' {
  export * from './types/client/router';
}

declare module '@windy/router.d' {
  export * from './types/client/router';
}

declare module '@windy/client/router' {
  export * from './types/client/router';
}

declare module '@windy/client/router.d' {
  export * from './types/client/router';
}

declare module '@windy/semaphore' {
  export * from './types/client/semaphore';
}

declare module '@windy/semaphore.d' {
  export * from './types/client/semaphore';
}

declare module '@windy/client/semaphore' {
  export * from './types/client/semaphore';
}

declare module '@windy/client/semaphore.d' {
  export * from './types/client/semaphore';
}

declare module '@windy/seoParser' {
  export * from './types/client/seoParser';
  export { default } from './types/client/seoParser';
}

declare module '@windy/seoParser.d' {
  export * from './types/client/seoParser';
  export { default } from './types/client/seoParser';
}

declare module '@windy/client/seoParser' {
  export * from './types/client/seoParser';
  export { default } from './types/client/seoParser';
}

declare module '@windy/client/seoParser.d' {
  export * from './types/client/seoParser';
  export { default } from './types/client/seoParser';
}

declare module '@windy/serviceWorker' {
  export * from './types/client/serviceWorker';
}

declare module '@windy/serviceWorker.d' {
  export * from './types/client/serviceWorker';
}

declare module '@windy/client/serviceWorker' {
  export * from './types/client/serviceWorker';
}

declare module '@windy/client/serviceWorker.d' {
  export * from './types/client/serviceWorker';
}

declare module '@windy/serviceWorkerCtrl' {
  export * from './types/client/serviceWorkerCtrl';
}

declare module '@windy/serviceWorkerCtrl.d' {
  export * from './types/client/serviceWorkerCtrl';
}

declare module '@windy/client/serviceWorkerCtrl' {
  export * from './types/client/serviceWorkerCtrl';
}

declare module '@windy/client/serviceWorkerCtrl.d' {
  export * from './types/client/serviceWorkerCtrl';
}

declare module '@windy/share' {
  export * from './types/client/share';
}

declare module '@windy/share.d' {
  export * from './types/client/share';
}

declare module '@windy/client/share' {
  export * from './types/client/share';
}

declare module '@windy/client/share.d' {
  export * from './types/client/share';
}

declare module '@windy/showMyPosition' {
  export * from './types/client/showMyPosition';
}

declare module '@windy/showMyPosition.d' {
  export * from './types/client/showMyPosition';
}

declare module '@windy/client/showMyPosition' {
  export * from './types/client/showMyPosition';
}

declare module '@windy/client/showMyPosition.d' {
  export * from './types/client/showMyPosition';
}

declare module '@windy/showableErrorsService' {
  export * from './types/client/showableErrorsService';
}

declare module '@windy/showableErrorsService.d' {
  export * from './types/client/showableErrorsService';
}

declare module '@windy/client/showableErrorsService' {
  export * from './types/client/showableErrorsService';
}

declare module '@windy/client/showableErrorsService.d' {
  export * from './types/client/showableErrorsService';
}

declare module '@windy/singleclick' {
  export * from './types/client/singleclick';
}

declare module '@windy/singleclick.d' {
  export * from './types/client/singleclick';
}

declare module '@windy/client/singleclick' {
  export * from './types/client/singleclick';
}

declare module '@windy/client/singleclick.d' {
  export * from './types/client/singleclick';
}

declare module '@windy/startup' {
  export * from './types/client/startup';
}

declare module '@windy/startup.d' {
  export * from './types/client/startup';
}

declare module '@windy/client/startup' {
  export * from './types/client/startup';
}

declare module '@windy/client/startup.d' {
  export * from './types/client/startup';
}

declare module '@windy/startupUtils' {
  export * from './types/client/startupUtils';
}

declare module '@windy/startupUtils.d' {
  export * from './types/client/startupUtils';
}

declare module '@windy/client/startupUtils' {
  export * from './types/client/startupUtils';
}

declare module '@windy/client/startupUtils.d' {
  export * from './types/client/startupUtils';
}

declare module '@windy/startupWeather' {
  export * from './types/client/startupWeather';
}

declare module '@windy/startupWeather.d' {
  export * from './types/client/startupWeather';
}

declare module '@windy/client/startupWeather' {
  export * from './types/client/startupWeather';
}

declare module '@windy/client/startupWeather.d' {
  export * from './types/client/startupWeather';
}

declare module '@windy/storage' {
  export * from './types/client/storage';
  export { default } from './types/client/storage';
}

declare module '@windy/storage.d' {
  export * from './types/client/storage';
  export { default } from './types/client/storage';
}

declare module '@windy/client/storage' {
  export * from './types/client/storage';
  export { default } from './types/client/storage';
}

declare module '@windy/client/storage.d' {
  export * from './types/client/storage';
  export { default } from './types/client/storage';
}

declare module '@windy/store' {
  export * from './types/client/store';
  export { default } from './types/client/store';
}

declare module '@windy/store.d' {
  export * from './types/client/store';
  export { default } from './types/client/store';
}

declare module '@windy/client/store' {
  export * from './types/client/store';
  export { default } from './types/client/store';
}

declare module '@windy/client/store.d' {
  export * from './types/client/store';
  export { default } from './types/client/store';
}

declare module '@windy/storeLastPosition' {
  export * from './types/client/storeLastPosition';
}

declare module '@windy/storeLastPosition.d' {
  export * from './types/client/storeLastPosition';
}

declare module '@windy/client/storeLastPosition' {
  export * from './types/client/storeLastPosition';
}

declare module '@windy/client/storeLastPosition.d' {
  export * from './types/client/storeLastPosition';
}

declare module '@windy/subscription' {
  export * from './types/client/subscription';
}

declare module '@windy/subscription.d' {
  export * from './types/client/subscription';
}

declare module '@windy/client/subscription' {
  export * from './types/client/subscription';
}

declare module '@windy/client/subscription.d' {
  export * from './types/client/subscription';
}

declare module '@windy/swDownloader' {
  export * from './types/client/swDownloader';
}

declare module '@windy/swDownloader.d' {
  export * from './types/client/swDownloader';
}

declare module '@windy/client/swDownloader' {
  export * from './types/client/swDownloader';
}

declare module '@windy/client/swDownloader.d' {
  export * from './types/client/swDownloader';
}

declare module '@windy/swProxy' {
  export * from './types/client/swProxy';
}

declare module '@windy/swProxy.d' {
  export * from './types/client/swProxy';
}

declare module '@windy/client/swProxy' {
  export * from './types/client/swProxy';
}

declare module '@windy/client/swProxy.d' {
  export * from './types/client/swProxy';
}

declare module '@windy/swUtils' {
  export * from './types/client/swUtils';
}

declare module '@windy/swUtils.d' {
  export * from './types/client/swUtils';
}

declare module '@windy/client/swUtils' {
  export * from './types/client/swUtils';
}

declare module '@windy/client/swUtils.d' {
  export * from './types/client/swUtils';
}

declare module '@windy/throttler' {
  export * from './types/client/throttler';
}

declare module '@windy/throttler.d' {
  export * from './types/client/throttler';
}

declare module '@windy/client/throttler' {
  export * from './types/client/throttler';
}

declare module '@windy/client/throttler.d' {
  export * from './types/client/throttler';
}

declare module '@windy/tileHelpers' {
  export * from './types/client/tileHelpers';
}

declare module '@windy/tileHelpers.d' {
  export * from './types/client/tileHelpers';
}

declare module '@windy/client/tileHelpers' {
  export * from './types/client/tileHelpers';
}

declare module '@windy/client/tileHelpers.d' {
  export * from './types/client/tileHelpers';
}

declare module '@windy/tileInterpolator' {
  export * from './types/client/tileInterpolator';
}

declare module '@windy/tileInterpolator.d' {
  export * from './types/client/tileInterpolator';
}

declare module '@windy/client/tileInterpolator' {
  export * from './types/client/tileInterpolator';
}

declare module '@windy/client/tileInterpolator.d' {
  export * from './types/client/tileInterpolator';
}

declare module '@windy/tileLayerInstance' {
  export * from './types/client/tileLayerInstance';
}

declare module '@windy/tileLayerInstance.d' {
  export * from './types/client/tileLayerInstance';
}

declare module '@windy/client/tileLayerInstance' {
  export * from './types/client/tileLayerInstance';
}

declare module '@windy/client/tileLayerInstance.d' {
  export * from './types/client/tileLayerInstance';
}

declare module '@windy/tileLayerInterpolator' {
  export * from './types/client/tileLayerInterpolator';
}

declare module '@windy/tileLayerInterpolator.d' {
  export * from './types/client/tileLayerInterpolator';
}

declare module '@windy/client/tileLayerInterpolator' {
  export * from './types/client/tileLayerInterpolator';
}

declare module '@windy/client/tileLayerInterpolator.d' {
  export * from './types/client/tileLayerInterpolator';
}

declare module '@windy/tileLayerSource' {
  export * from './types/client/tileLayerSource';
}

declare module '@windy/tileLayerSource.d' {
  export * from './types/client/tileLayerSource';
}

declare module '@windy/client/tileLayerSource' {
  export * from './types/client/tileLayerSource';
}

declare module '@windy/client/tileLayerSource.d' {
  export * from './types/client/tileLayerSource';
}

declare module '@windy/timeAnimation' {
  export * from './types/client/timeAnimation';
}

declare module '@windy/timeAnimation.d' {
  export * from './types/client/timeAnimation';
}

declare module '@windy/client/timeAnimation' {
  export * from './types/client/timeAnimation';
}

declare module '@windy/client/timeAnimation.d' {
  export * from './types/client/timeAnimation';
}

declare module '@windy/timestampUtils' {
  export * from './types/client/timestampUtils';
}

declare module '@windy/timestampUtils.d' {
  export * from './types/client/timestampUtils';
}

declare module '@windy/client/timestampUtils' {
  export * from './types/client/timestampUtils';
}

declare module '@windy/client/timestampUtils.d' {
  export * from './types/client/timestampUtils';
}

declare module '@windy/timestampUtils.test' {
  export * from './types/client/timestampUtils.test';
}

declare module '@windy/timestampUtils.test.d' {
  export * from './types/client/timestampUtils.test';
}

declare module '@windy/client/timestampUtils.test' {
  export * from './types/client/timestampUtils.test';
}

declare module '@windy/client/timestampUtils.test.d' {
  export * from './types/client/timestampUtils.test';
}

declare module '@windy/topMessage' {
  export * from './types/client/topMessage';
}

declare module '@windy/topMessage.d' {
  export * from './types/client/topMessage';
}

declare module '@windy/client/topMessage' {
  export * from './types/client/topMessage';
}

declare module '@windy/client/topMessage.d' {
  export * from './types/client/topMessage';
}

declare module '@windy/trans' {
  export * from './types/client/trans';
}

declare module '@windy/trans.d' {
  export * from './types/client/trans';
}

declare module '@windy/client/trans' {
  export * from './types/client/trans';
}

declare module '@windy/client/trans.d' {
  export * from './types/client/trans';
}

declare module '@windy/typeGuards' {
  export * from './types/client/typeGuards';
}

declare module '@windy/typeGuards.d' {
  export * from './types/client/typeGuards';
}

declare module '@windy/client/typeGuards' {
  export * from './types/client/typeGuards';
}

declare module '@windy/client/typeGuards.d' {
  export * from './types/client/typeGuards';
}

declare module '@windy/user' {
  export * from './types/client/user';
}

declare module '@windy/user.d' {
  export * from './types/client/user';
}

declare module '@windy/client/user' {
  export * from './types/client/user';
}

declare module '@windy/client/user.d' {
  export * from './types/client/user';
}

declare module '@windy/userAlerts' {
  export * from './types/client/userAlerts';
}

declare module '@windy/userAlerts.d' {
  export * from './types/client/userAlerts';
}

declare module '@windy/client/userAlerts' {
  export * from './types/client/userAlerts';
}

declare module '@windy/client/userAlerts.d' {
  export * from './types/client/userAlerts';
}

declare module '@windy/userAlertsEnums' {
  export * from './types/client/userAlertsEnums';
}

declare module '@windy/userAlertsEnums.d' {
  export * from './types/client/userAlertsEnums';
}

declare module '@windy/client/userAlertsEnums' {
  export * from './types/client/userAlertsEnums';
}

declare module '@windy/client/userAlertsEnums.d' {
  export * from './types/client/userAlertsEnums';
}

declare module '@windy/userConsent' {
  export * from './types/client/userConsent';
}

declare module '@windy/userConsent.d' {
  export * from './types/client/userConsent';
}

declare module '@windy/client/userConsent' {
  export * from './types/client/userConsent';
}

declare module '@windy/client/userConsent.d' {
  export * from './types/client/userConsent';
}

declare module '@windy/userFavs' {
  export * from './types/client/userFavs';
}

declare module '@windy/userFavs.d' {
  export * from './types/client/userFavs';
}

declare module '@windy/client/userFavs' {
  export * from './types/client/userFavs';
}

declare module '@windy/client/userFavs.d' {
  export * from './types/client/userFavs';
}

declare module '@windy/utils' {
  export * from './types/client/utils';
}

declare module '@windy/utils.d' {
  export * from './types/client/utils';
}

declare module '@windy/client/utils' {
  export * from './types/client/utils';
}

declare module '@windy/client/utils.d' {
  export * from './types/client/utils';
}

declare module '@windy/utils.test' {
  export * from './types/client/utils.test';
}

declare module '@windy/utils.test.d' {
  export * from './types/client/utils.test';
}

declare module '@windy/client/utils.test' {
  export * from './types/client/utils.test';
}

declare module '@windy/client/utils.test.d' {
  export * from './types/client/utils.test';
}

declare module '@windy/visibility' {
  export * from './types/client/visibility';
}

declare module '@windy/visibility.d' {
  export * from './types/client/visibility';
}

declare module '@windy/client/visibility' {
  export * from './types/client/visibility';
}

declare module '@windy/client/visibility.d' {
  export * from './types/client/visibility';
}

declare module '@windy/client/d.ts.files/GlObj' {
  export * from './types/client/d.ts.files/GlObj';
}

declare module '@windy/client/d.ts.files/GlObj.d' {
  export * from './types/client/d.ts.files/GlObj';
}

declare module '@windy/client/d.ts.files/LabelsLayer' {
  export * from './types/client/d.ts.files/LabelsLayer';
}

declare module '@windy/client/d.ts.files/LabelsLayer.d' {
  export * from './types/client/d.ts.files/LabelsLayer';
}

declare module '@windy/client/d.ts.files/Metric' {
  export * from './types/client/d.ts.files/Metric';
}

declare module '@windy/client/d.ts.files/Metric.d' {
  export * from './types/client/d.ts.files/Metric';
}

declare module '@windy/client/d.ts.files/alerts' {
  export * from './types/client/d.ts.files/alerts';
}

declare module '@windy/client/d.ts.files/alerts.d' {
  export * from './types/client/d.ts.files/alerts';
}

declare module '@windy/client/d.ts.files/broadcast' {
  export * from './types/client/d.ts.files/broadcast';
}

declare module '@windy/client/d.ts.files/broadcast.d' {
  export * from './types/client/d.ts.files/broadcast';
}

declare module '@windy/client/d.ts.files/dataSpecifications' {
  export * from './types/client/d.ts.files/dataSpecifications';
}

declare module '@windy/client/d.ts.files/dataSpecifications.d' {
  export * from './types/client/d.ts.files/dataSpecifications';
}

declare module '@windy/favs' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/favs.d' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/client/favs' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/client/favs.d' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/client/d.ts.files/favs' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/client/d.ts.files/favs.d' {
  export * from './types/client/d.ts.files/favs';
}

declare module '@windy/client/d.ts.files/format' {
  export * from './types/client/d.ts.files/format';
}

declare module '@windy/client/d.ts.files/format.d' {
  export * from './types/client/d.ts.files/format';
}

declare module '@windy/client/d.ts.files/glUtils' {
  export * from './types/client/d.ts.files/glUtils';
}

declare module '@windy/client/d.ts.files/glUtils.d' {
  export * from './types/client/d.ts.files/glUtils';
}

declare module '@windy/client/d.ts.files/http' {
  export * from './types/client/d.ts.files/http';
}

declare module '@windy/client/d.ts.files/http.d' {
  export * from './types/client/d.ts.files/http';
}

declare module '@windy/incomingMessages' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/incomingMessages.d' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/client/incomingMessages' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/client/incomingMessages.d' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/client/d.ts.files/incomingMessages' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/client/d.ts.files/incomingMessages.d' {
  export * from './types/client/d.ts.files/incomingMessages';
}

declare module '@windy/interpolatorTypes' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/interpolatorTypes.d' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/client/interpolatorTypes' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/client/interpolatorTypes.d' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/client/d.ts.files/interpolatorTypes' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/client/d.ts.files/interpolatorTypes.d' {
  export * from './types/client/d.ts.files/interpolatorTypes';
}

declare module '@windy/client/d.ts.files/legends' {
  export * from './types/client/d.ts.files/legends';
}

declare module '@windy/client/d.ts.files/legends.d' {
  export * from './types/client/d.ts.files/legends';
}

declare module '@windy/client/d.ts.files/lib' {
  export * from './types/client/d.ts.files/lib';
}

declare module '@windy/client/d.ts.files/lib.d' {
  export * from './types/client/d.ts.files/lib';
}

declare module '@windy/client/d.ts.files/liveAlerts' {
  export * from './types/client/d.ts.files/liveAlerts';
}

declare module '@windy/client/d.ts.files/liveAlerts.d' {
  export * from './types/client/d.ts.files/liveAlerts';
}

declare module '@windy/client/d.ts.files/mapUtils' {
  export * from './types/client/d.ts.files/mapUtils';
}

declare module '@windy/client/d.ts.files/mapUtils.d' {
  export * from './types/client/d.ts.files/mapUtils';
}

declare module '@windy/client/d.ts.files/notifications' {
  export * from './types/client/d.ts.files/notifications';
}

declare module '@windy/client/d.ts.files/notifications.d' {
  export * from './types/client/d.ts.files/notifications';
}

declare module '@windy/outgoingMessages' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/outgoingMessages.d' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/client/outgoingMessages' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/client/outgoingMessages.d' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/client/d.ts.files/outgoingMessages' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/client/d.ts.files/outgoingMessages.d' {
  export * from './types/client/d.ts.files/outgoingMessages';
}

declare module '@windy/plugin-params' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/plugin-params.d' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/client/plugin-params' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/client/plugin-params.d' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/client/d.ts.files/plugin-params' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/client/d.ts.files/plugin-params.d' {
  export * from './types/client/d.ts.files/plugin-params';
}

declare module '@windy/client/d.ts.files/plugins' {
  export * from './types/client/d.ts.files/plugins';
}

declare module '@windy/client/d.ts.files/plugins.d' {
  export * from './types/client/d.ts.files/plugins';
}

declare module '@windy/client/d.ts.files/pois' {
  export * from './types/client/d.ts.files/pois';
}

declare module '@windy/client/d.ts.files/pois.d' {
  export * from './types/client/d.ts.files/pois';
}

declare module '@windy/client/d.ts.files/rootScope' {
  export * from './types/client/d.ts.files/rootScope';
}

declare module '@windy/client/d.ts.files/rootScope.d' {
  export * from './types/client/d.ts.files/rootScope';
}

declare module '@windy/satellite' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/satellite.d' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/client/satellite' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/client/satellite.d' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/client/d.ts.files/satellite' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/client/d.ts.files/satellite.d' {
  export * from './types/client/d.ts.files/satellite';
}

declare module '@windy/shaders' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/shaders.d' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/client/shaders' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/client/shaders.d' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/client/d.ts.files/shaders' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/client/d.ts.files/shaders.d' {
  export * from './types/client/d.ts.files/shaders';
}

declare module '@windy/client/d.ts.files/singleclick' {
  export * from './types/client/d.ts.files/singleclick';
}

declare module '@windy/client/d.ts.files/singleclick.d' {
  export * from './types/client/d.ts.files/singleclick';
}

declare module '@windy/client/d.ts.files/storage' {
  export * from './types/client/d.ts.files/storage';
}

declare module '@windy/client/d.ts.files/storage.d' {
  export * from './types/client/d.ts.files/storage';
}

declare module '@windy/client/d.ts.files/store' {
  export * from './types/client/d.ts.files/store';
}

declare module '@windy/client/d.ts.files/store.d' {
  export * from './types/client/d.ts.files/store';
}

declare module '@windy/client/d.ts.files/user' {
  export * from './types/client/d.ts.files/user';
}

declare module '@windy/client/d.ts.files/user.d' {
  export * from './types/client/d.ts.files/user';
}

declare module '@windy/webcams' {
  export * from './types/client/d.ts.files/webcams';
}

declare module '@windy/webcams.d' {
  export * from './types/client/d.ts.files/webcams';
}

declare module '@windy/client/webcams' {
  export * from './types/client/d.ts.files/webcams';
}

declare module '@windy/client/webcams.d' {
  export * from './types/client/d.ts.files/webcams';
}

declare module '@windy/client/d.ts.files/webcams' {
  export * from './types/client/d.ts.files/webcams';
}

declare module '@windy/client/d.ts.files/webcams.d' {
  export * from './types/client/d.ts.files/webcams';
}
