runtime: nodejs16

instance_class: F1

automatic_scaling:
  max_instances: 3
  max_concurrent_requests: 80
  target_throughput_utilization: 0.95
  target_cpu_utilization: 0.95
  max_pending_latency: 500ms
  min_pending_latency: 400ms

handlers:
- url: /esri
  static_dir: frontend/static/esri
  secure: always
  redirect_http_response_code: 301

- url: /models
  static_dir: frontend/static/models
  expiration: "2d"
  secure: always
  redirect_http_response_code: 301

- url: /img
  static_dir: frontend/static/img
  expiration: "2d"
  secure: always
  redirect_http_response_code: 301

- url: /js
  static_dir: frontend/static/js
  secure: always
  redirect_http_response_code: 301

- url: /css
  static_dir: frontend/static/css
  secure: always
  redirect_http_response_code: 301

- url: /favicon\.ico$
  static_files: frontend/static/favicon.ico
  upload: frontend/static/favicon\.ico$
  expiration: "2d"
  secure: always
  redirect_http_response_code: 301

- url: /robots\.txt$
  static_files: frontend/static/robots.txt
  upload: frontend/static/robots\.txt$
  expiration: "2d"
  secure: always
  redirect_http_response_code: 301

- url: /3d$
  static_files: frontend/static/index.html
  upload: frontend/static/index.html
  secure: always
  redirect_http_response_code: 301

- url: /$
  static_files: frontend/static/index.html
  upload: frontend/static/index.html
  secure: always
  redirect_http_response_code: 301

- url: /archives.html$
  static_files: frontend/static/archives.html
  upload: frontend/static/archives.html
  secure: always
  redirect_http_response_code: 301

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto