packages:
  - apps/*
  - libs/*

catalog:
  '@date-fns/tz': '1.4.1'
  '@dotenvx/dotenvx': '^1.51.4'
  '@google-cloud/datastore': '^10.0.1'
  '@google-cloud/pubsub': '^5.2.0'
  '@google-cloud/storage': '^7.18.0'
  '@reduxjs/toolkit': '^2.11.2'
  '@types/compression': '^1.8.1'
  '@types/cors': '^2.8.19'
  '@types/csurf': '^1.11.5'
  '@types/d3-array': '^3.2.2'
  '@types/express': '^5.0.0'
  '@types/express-fileupload': '^1.5.1'
  '@types/express-session': '^1.18.1'
  '@types/google.maps': '^3.58.1'
  '@types/mapbox__sphericalmercator': '^1.2.3'
  '@types/node-os-utils': '^1.3.4'
  '@types/react': '^18.3.13'
  '@types/react-redux': '^7.1.34'
  '@types/validator': '^13.12.2'
  '@xmldom/xmldom': '^0.8.10'
  'commander': '^12.1.0'
  'date-fns': '^4.1.0'
  'express': '^5.0.1'
  'geolib': '^3.3.4'
  'glob': '^11.0.3'
  'grant': '^5.4.24'
  'ioredis': '^5.8.2'
  'jsonc-eslint-parser': '2.4.0'
  'lit': '^3.3.2'
  'mapbox-vector-tile': '^0.3.0'
  'simplify-path': '^1.1.0'
  'tslib': '^2.8.1'
  'vite': '~5.3.1'
  'zod': '^3.24.4'
