declare const SECRETS: {
  GEONAMES: string;
  REDIS_URL_DEV: string;
  REDIS_URL: string;
  GOOGLE_OAUTH_ID: string;
  GOOGLE_OAUTH_SECRET: string;
  SESSION_SECRET: string;
  FLYME_TOKEN: string;
  ADMINS: string;
  PROXY_KEY: string;
  OPENAIP_KEY: string;
  AVIANT_URL: string;
  APRS_USER: string;
  APRS_PASSWORD: string;
  ZOLEO_API_KEY: string;
  ZOLEO_PUSH_USER: string;
  ZOLEO_PUSH_PWD: string;
  XCONTEST_JWT: string;
  FLYMASTER_GROUP_ID: string;
  FLYMASTER_GROUP_TOKEN: string;
  MAILERSEND_TOKEN: string;
  MESHBIR_AUTH_TOKEN: string;
  ZIPLINE_TOKEN: string;
  WING_TOKEN: string;
  EXPORT_ID_SALT: string;
};
