/**
 * flyXC service worker.
 *
 * Coordinates caching, offline support, and seamless app updates without redundant reloads.
 *
 * IMPORTANT:
 * Do not rename/move this file, it is referenced in apps/fxc-front/pwa.config.ts
 */

import type { ManifestEntry } from 'workbox-build';
import { googleFontsCache } from 'workbox-recipes';
import { registerRoute, setDefaultHandler } from 'workbox-routing';
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies';

import { cleanupOldCache, isCacheableAssetUrl, isIndexRouteUrl } from './app/logic/pwa-lifecycle';

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: Array<ManifestEntry> };

/** Dedicated cache bucket for HTML navigation routes (/ , /3d, etc.). */
export const FLYXC_PAGES_CACHE_NAME = 'flyxc-pages-v1';
/** Dedicated cache bucket for static hashed frontend assets (JS, CSS, images, 3D models). */
export const FLYXC_ASSET_CACHE_NAME = 'flyxc-assets-v1';

export const CURRENT_CACHE_NAMES = [FLYXC_PAGES_CACHE_NAME, FLYXC_ASSET_CACHE_NAME];

// 1. Navigation Routes:
// Try to fetch navigation pages from the network first, caching the response in FLYXC_PAGES_CACHE_NAME.
// If offline, the cached HTML document is served.
const isIndexRoute = ({ url }: { url: URL }): boolean => isIndexRouteUrl(url.pathname);
registerRoute(isIndexRoute, new NetworkFirst({ cacheName: FLYXC_PAGES_CACHE_NAME, networkTimeoutSeconds: 10 }));

// 2. Static Assets:
// Build manifest URLs generated by vite-plugin-pwa.
const manifest = self.__WB_MANIFEST;

export const manifestURLs = new Set(
  manifest.map((entry) => {
    const url = new URL(entry.url, String(self.location));
    return url.href;
  }),
);

export { cleanupOldCache };

// Serve hashed assets from cache first. Explicitly admits generated-manifest URLs and
// explicitly required static assets (/static/), while excluding query variants, non-static
// resources, and /sw.js.
const flyxcAssetHost = new URL(import.meta.env.VITE_APP_SERVER).host;
const isCacheableAsset = ({ url, request }: { url: URL; request?: Request }): boolean => {
  // Navigation requests must never be handled by CacheFirst; they belong to the NetworkFirst flow.
  if (request?.mode === 'navigate') {
    return false;
  }
  return isCacheableAssetUrl(url, flyxcAssetHost, manifestURLs);
};
registerRoute(isCacheableAsset, new CacheFirst({ cacheName: FLYXC_ASSET_CACHE_NAME }));

// Cache Google Fonts.
googleFontsCache();

// Fallback to the network for any unhandled requests.
setDefaultHandler(new NetworkOnly());

// Immediately activate newly installed service workers.
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Coordinated activation:
// 1. Delete legacy / obsolete cache buckets (e.g., 'flyxc-cache-v1').
// 2. Evict obsolete hashed assets from FLYXC_ASSET_CACHE_NAME using manifestURLs.
// 3. Claim clients ONLY AFTER cache cleanup completes to prevent race condition reloads.
// 4. Notify clients of the active version so fresh pages know not to trigger redundant reloads.
self.addEventListener('activate', (event: ExtendableEvent) => {
  event.waitUntil(
    (async () => {
      // Clean up legacy cache databases
      const cacheKeys = await caches.keys();
      for (const key of cacheKeys) {
        if (!CURRENT_CACHE_NAMES.includes(key) && !key.startsWith('google-fonts')) {
          if (import.meta.env.DEV) {
            console.log(`Deleting obsolete cache bucket: ${key}`);
          }
          await caches.delete(key);
        }
      }

      // Evict outdated hashed assets
      await cleanupOldCache(FLYXC_ASSET_CACHE_NAME, manifestURLs, import.meta.env.DEV);

      // Claim clients only after cache cleanup is done
      await self.clients.claim();

      // Notify clients of the active version
      const clients = await self.clients.matchAll({ type: 'window' });
      for (const client of clients) {
        client.postMessage({
          type: 'SW_ACTIVATED',
          version: __BUILD_TIMESTAMP__ ?? '',
        });
      }
    })(),
  );
});

// Respond to version queries from client pages.
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data?.type === 'GET_VERSION') {
    event.ports?.[0]?.postMessage({
      version: __BUILD_TIMESTAMP__ ?? '',
    });
  }
});
