'use strict'; // code generated by pbf v3.2.1

// Track ========================================

var Track = (exports.Track = {});

Track.read = function (pbf, end) {
  return pbf.readFields(Track._readField, { pilot: '', lat: [], lon: [], alt: [], ts: [] }, end);
};
Track._readField = function (tag, obj, pbf) {
  if (tag === 1) obj.pilot = pbf.readString();
  else if (tag === 2) pbf.readPackedSVarint(obj.lat);
  else if (tag === 3) pbf.readPackedSVarint(obj.lon);
  else if (tag === 4) pbf.readPackedSVarint(obj.alt);
  else if (tag === 5) pbf.readPackedVarint(obj.ts);
};
Track.write = function (obj, pbf) {
  if (obj.pilot) pbf.writeStringField(1, obj.pilot);
  if (obj.lat) pbf.writePackedSVarint(2, obj.lat);
  if (obj.lon) pbf.writePackedSVarint(3, obj.lon);
  if (obj.alt) pbf.writePackedSVarint(4, obj.alt);
  if (obj.ts) pbf.writePackedVarint(5, obj.ts);
};

// TrackGroup ========================================

var TrackGroup = (exports.TrackGroup = {});

TrackGroup.read = function (pbf, end) {
  return pbf.readFields(TrackGroup._readField, { tracks: [] }, end);
};
TrackGroup._readField = function (tag, obj, pbf) {
  if (tag === 2) obj.tracks.push(Track.read(pbf, pbf.readVarint() + pbf.pos));
};
TrackGroup.write = function (obj, pbf) {
  if (obj.tracks) for (var i = 0; i < obj.tracks.length; i++) pbf.writeMessage(2, Track.write, obj.tracks[i]);
};

// GroundAltitude ========================================

var GroundAltitude = (exports.GroundAltitude = {});

GroundAltitude.read = function (pbf, end) {
  return pbf.readFields(GroundAltitude._readField, { altitudes: [], has_errors: false }, end);
};
GroundAltitude._readField = function (tag, obj, pbf) {
  if (tag === 1) pbf.readPackedSVarint(obj.altitudes);
  else if (tag === 2) obj.has_errors = pbf.readBoolean();
};
GroundAltitude.write = function (obj, pbf) {
  if (obj.altitudes) pbf.writePackedSVarint(1, obj.altitudes);
  if (obj.has_errors) pbf.writeBooleanField(2, obj.has_errors);
};

// GroundAltitudeGroup ========================================

var GroundAltitudeGroup = (exports.GroundAltitudeGroup = {});

GroundAltitudeGroup.read = function (pbf, end) {
  return pbf.readFields(GroundAltitudeGroup._readField, { ground_altitudes: [] }, end);
};
GroundAltitudeGroup._readField = function (tag, obj, pbf) {
  if (tag === 1) obj.ground_altitudes.push(GroundAltitude.read(pbf, pbf.readVarint() + pbf.pos));
};
GroundAltitudeGroup.write = function (obj, pbf) {
  if (obj.ground_altitudes)
    for (var i = 0; i < obj.ground_altitudes.length; i++)
      pbf.writeMessage(1, GroundAltitude.write, obj.ground_altitudes[i]);
};

// MetaTrackGroup ========================================

var MetaTrackGroup = (exports.MetaTrackGroup = {});

MetaTrackGroup.read = function (pbf, end) {
  return pbf.readFields(
    MetaTrackGroup._readField,
    { id: 0, num_postprocess: 0, track_group_bin: null, ground_altitude_group_bin: null },
    end,
  );
};
MetaTrackGroup._readField = function (tag, obj, pbf) {
  if (tag === 1) obj.id = pbf.readVarint(true);
  else if (tag === 2) obj.num_postprocess = pbf.readVarint();
  else if (tag === 3) obj.track_group_bin = pbf.readBytes();
  else if (tag === 4) obj.ground_altitude_group_bin = pbf.readBytes();
};
MetaTrackGroup.write = function (obj, pbf) {
  if (obj.id) pbf.writeVarintField(1, obj.id);
  if (obj.num_postprocess) pbf.writeVarintField(2, obj.num_postprocess);
  if (obj.track_group_bin) pbf.writeBytesField(3, obj.track_group_bin);
  if (obj.ground_altitude_group_bin) pbf.writeBytesField(4, obj.ground_altitude_group_bin);
};

// MetaTracks ========================================

var MetaTracks = (exports.MetaTracks = {});

MetaTracks.read = function (pbf, end) {
  return pbf.readFields(MetaTracks._readField, { meta_track_groups_bin: [] }, end);
};
MetaTracks._readField = function (tag, obj, pbf) {
  if (tag === 1) obj.meta_track_groups_bin.push(pbf.readBytes());
};
MetaTracks.write = function (obj, pbf) {
  if (obj.meta_track_groups_bin)
    for (var i = 0; i < obj.meta_track_groups_bin.length; i++) pbf.writeBytesField(1, obj.meta_track_groups_bin[i]);
};
