// Import all used ionic components.

import { initialize } from '@ionic/core/components';
import { defineCustomElement as d1 } from '@ionic/core/components/ion-accordion';
import { defineCustomElement as d2 } from '@ionic/core/components/ion-accordion-group';
import { defineCustomElement as d3 } from '@ionic/core/components/ion-alert';
import { defineCustomElement as d4 } from '@ionic/core/components/ion-app';
import { defineCustomElement as d5 } from '@ionic/core/components/ion-backdrop';
import { defineCustomElement as d6 } from '@ionic/core/components/ion-badge';
import { defineCustomElement as d7 } from '@ionic/core/components/ion-button';
import { defineCustomElement as d8 } from '@ionic/core/components/ion-buttons';
import { defineCustomElement as d9 } from '@ionic/core/components/ion-card';
import { defineCustomElement as d10 } from '@ionic/core/components/ion-card-header';
import { defineCustomElement as d11 } from '@ionic/core/components/ion-card-title';
import { defineCustomElement as d12 } from '@ionic/core/components/ion-checkbox';
import { defineCustomElement as d13 } from '@ionic/core/components/ion-col';
import { defineCustomElement as d14 } from '@ionic/core/components/ion-content';
import { defineCustomElement as d15 } from '@ionic/core/components/ion-fab-button';
import { defineCustomElement as d16 } from '@ionic/core/components/ion-footer';
import { defineCustomElement as d17 } from '@ionic/core/components/ion-grid';
import { defineCustomElement as d18 } from '@ionic/core/components/ion-header';
import { defineCustomElement as d19 } from '@ionic/core/components/ion-input';
import { defineCustomElement as d20 } from '@ionic/core/components/ion-item';
import { defineCustomElement as d21 } from '@ionic/core/components/ion-item-divider';
import { defineCustomElement as d22 } from '@ionic/core/components/ion-label';
import { defineCustomElement as d23 } from '@ionic/core/components/ion-list';
import { defineCustomElement as d24 } from '@ionic/core/components/ion-menu';
import { defineCustomElement as d25 } from '@ionic/core/components/ion-menu-button';
import { defineCustomElement as d26 } from '@ionic/core/components/ion-menu-toggle';
import { defineCustomElement as d27 } from '@ionic/core/components/ion-modal';
import { defineCustomElement as d28 } from '@ionic/core/components/ion-note';
import { defineCustomElement as d29 } from '@ionic/core/components/ion-popover';
import { defineCustomElement as d30 } from '@ionic/core/components/ion-progress-bar';
import { defineCustomElement as d31 } from '@ionic/core/components/ion-radio';
import { defineCustomElement as d32 } from '@ionic/core/components/ion-radio-group';
import { defineCustomElement as d33 } from '@ionic/core/components/ion-range';
import { defineCustomElement as d34 } from '@ionic/core/components/ion-ripple-effect';
import { defineCustomElement as d35 } from '@ionic/core/components/ion-route';
import { defineCustomElement as d36 } from '@ionic/core/components/ion-router-outlet';
import { defineCustomElement as d37 } from '@ionic/core/components/ion-row';
import { defineCustomElement as d48 } from '@ionic/core/components/ion-searchbar';
import { defineCustomElement as d38 } from '@ionic/core/components/ion-segment';
import { defineCustomElement as d39 } from '@ionic/core/components/ion-segment-button';
import { defineCustomElement as d40 } from '@ionic/core/components/ion-select';
import { defineCustomElement as d41 } from '@ionic/core/components/ion-select-option';
import { defineCustomElement as d42 } from '@ionic/core/components/ion-select-popover';
import { defineCustomElement as d49 } from '@ionic/core/components/ion-split-pane';
import { defineCustomElement as d43 } from '@ionic/core/components/ion-text';
import { defineCustomElement as d44 } from '@ionic/core/components/ion-title';
import { defineCustomElement as d45 } from '@ionic/core/components/ion-toast';
import { defineCustomElement as d46 } from '@ionic/core/components/ion-toggle';
import { defineCustomElement as d47 } from '@ionic/core/components/ion-toolbar';

import { defineCustomElement as d50 } from './ion-router';

export function ionicInit(): void {
  initialize();
  d1();
  d2();
  d3();
  d4();
  d5();
  d6();
  d7();
  d8();
  d9();
  d10();
  d11();
  d12();
  d13();
  d14();
  d15();
  d16();
  d17();
  d18();
  d19();
  d20();
  d21();
  d22();
  d23();
  d24();
  d25();
  d26();
  d27();
  d28();
  d29();
  d30();
  d31();
  d32();
  d33();
  d34();
  d35();
  d36();
  d37();
  d38();
  d39();
  d40();
  d41();
  d42();
  d43();
  d44();
  d45();
  d46();
  d47();
  d48();
  d49();
  d50();
}
