/**
 * This file is O B S O L E T E and not maintained anymore.
 */
/// <reference types="@windy/declarations/variables" />
import 'virtual:build-info';
export * as errorLogger from '../utils/errorLogger';
export * as Evented from '../utils/Evented';
export * as fetch from '../utils/fetch';
export * as format from '../utils/format';
export * as ga from '../utils/ga';
export * as http from '../utils/http';
export { default as lruCache } from '../utils/lruCache';
export { default as storage } from '../utils/storage';
export * as subscription from '../utils/subscription';
export * as utils from '../utils/utils';
export * as mapUtils from '../utils/mapUtils';
export * as customProtocol from '../utils/customProtocol';
export * as landLayer from '../map/landLayer';
export * as throttler from '../utils/throttler';
export * as Calendar from '../weatherClasses/Calendar';
export * as Color from '../weatherClasses/Color';
export * as Layer from '../weatherClasses/Layer';
export * as Metric from '../weatherClasses/Metric';
export * as MetricClasses from '../weatherClasses/MetricClasses';
export * as Overlay from '../weatherClasses/Overlay';
export * as OverlayClasses from '../weatherClasses/OverlayClasses';
export * as Product from '../weatherClasses/Product';
export { default as layers } from '../weather/layers';
export { default as metrics } from '../weather/metrics';
export * as models from '../weather/models';
export { default as overlays } from '../weather/overlays';
export { default as products } from '../weather/products';
export { default as broadcast } from '../services/broadcast';
export { default as colors } from '../services/colors';
export * as connection from '../services/connection';
export { default as dataSpecifications } from '../services/dataSpecifications';
export * as detectDevice from '../services/detectDevice';
export * as device from '../services/device';
export * as deviceLogging from '../services/deviceLogging';
export * as geolocation from '../services/geolocation';
export * as notifications from '../services/notifications';
export * as params from '../services/params';
export * as rootScope from '../services/rootScope';
export { default as store } from '../services/store';
export * as trans from '../services/trans';
export * as Plugin from '../pluginSystem/Plugin';
export * as SveltePanePlugin from '../pluginSystem/SveltePanePlugin';
export * as SveltePlugin from '../pluginSystem/SveltePlugin';
export * as TagPlugin from '../pluginSystem/TagPlugin';
export * as WindowPlugin from '../pluginSystem/WindowPlugin';
export { default as plugins } from '../pluginSystem/plugins';
export * as pluginsCtrl from '../pluginSystem/pluginsCtrl';
export * as BottomSlide from '../uiClasses/BottomSlide';
export * as Drag from '../uiClasses/Drag';
export * as Swipe from '../uiClasses/Swipe';
export * as Window from '../uiClasses/Window';
export * as rhMessage from '../ui/rhMessage';
export * as timeAnimation from '../ui/timeAnimation';
export * as visibility from '../ui/visibility';
export * as Renderer from '../renderClasses/Renderer';
export * as TileLayer from '../renderClasses/TileLayer';
export * as tileLayerSource from '../tileCache/tileLayerSource';
export * as switchableTileCache from '../tileCache/SwitchableTileCache';
export * as interpolator from '../render/interpolator';
export * as renderCtrl from '../render/renderCtrl';
export * as renderUtils from '../render/renderUtils';
export { default as renderers } from '../render/renderers';
export * as tileInterpolator from '../render/tileLayerInterpolator';
export { GlObj } from '../glUtils/glUtils';
export { default as LabelsLayer } from '../mapClasses/LabelsLayer';
export * as cityLabels from '../map/cityLabels';
export * as map from '../map/map';
export * as mapGlobeCtrl from '../map/mapGlobeCtrl';
export * as picker from '../map/picker';
export * as singleclick from '../map/singleclick';
export * as log from '../dummyModules/log';
export * as promo from '../dummyModules/promo';
export * as location from '../dummyModules/location';
export * as router from '../dummyModules/router';
export * as showableErrorsService from '../dummyModules/showableErrorsService';
export * as userFavs from '../dummyModules/userFavs';
export { default as libHtml } from '../lib/libHtml';
