import { Product } from '@windy/Product';
import { AromeProduct, AccessProduct, AccessCProduct, EcmwfForecastProduct, EcmwfProduct, SatAndRadarPlusProduct } from '@windy/ProductClasses';
import type { Products } from '@windy/rootScope.d';
type AllExportedProducts = Implements<{
    [P in Products]: Product;
}, {
    bomAccess: AccessProduct;
    bomAccessAd: AccessCProduct;
    bomAccessBn: AccessCProduct;
    bomAccessDn: AccessCProduct;
    bomAccessNq: AccessCProduct;
    bomAccessPh: AccessCProduct;
    bomAccessSy: AccessCProduct;
    bomAccessVt: AccessCProduct;
    mblue: Product;
    ecmwf: EcmwfForecastProduct;
    ecmwfWaves: Product;
    ecmwfAnalysis: EcmwfProduct;
    canHrdps: Product;
    canRdwpsWaves: Product;
    cams: Product;
    camsEu: Product;
    cmems: Product;
    czeAladin: Product;
    gfs: Product;
    gfsWaves: Product;
    icon: Product;
    iconD2: Product;
    iconEu: Product;
    iconEuWaves: Product;
    arome: Product;
    aromeAntilles: AromeProduct;
    aromeFrance: AromeProduct;
    aromeReunion: AromeProduct;
    nems: Product;
    namAlaska: Product;
    namConus: Product;
    namHawaii: Product;
    capAlerts: Product;
    efi: Product;
    radar: Product;
    satellite: SatAndRadarPlusProduct;
    hrrrAlaska: Product;
    hrrrConus: Product;
    ukv: Product;
    drought: Product;
    fireDanger: Product;
    activeFires: Product;
    jmaMsm: Product;
    jmaCwmWaves: Product;
    topoMap: Product;
}>;
declare const products: AllExportedProducts;
export default products;
